### ISSUE TITLE
The Installer is Broken

### ISSUE THREAD

**Issue by 488GTB** [Open-Shell/Open-Shell-Menu#76] opened 2018-08-21 08:42 UTC
On my 3 systems, the Classic Shell installer worked fine.
The new OpenShell installer fails. 
It cannot terminate explorer.exe processes properly, even when run as Administrator.

The only way I can get OpenShell to install is to Ctl-Alt-Del and manually terminate explorer.exe.

**Comment by AveYo** [comment] 2018-08-21 10:44
For clarification, did you use the latest nightly `OpenShellSetup_4_4_131`?

**Comment by coddec** [comment] 2018-08-21 23:55
`OpenShellSetup_4_4_131`

https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts

**Comment by gardenman** [comment] 2018-08-23 01:45
Same for me, install is broken on 4.4.131. Only tested in 1 VM so far.
Version 4.4.109 was the same for me. On my desktop, and 2 VMs. I just manually closed them out and ran the install and then manually reopened them if I remember correctly.

More details, with version 4.4.131, it closes Explorer out, leaves a blue screen and acts like it still can't close it out. Eventually gives up and gives error "The setup was unable to automatically close all requested applications. Please ensure that the applications holding files in use are closed before continuing with the installation." ---- I pressed OK and it says "The following applications are using files that need to be updated....." and it lists "Classic Start Menu" and "Windows Explorer". It has the option to "Close the applications" automatically chosen. I hit OK.  It gives the same error "The setup was unable to automatically...". Press OK. And it appears to finish installing/copying files. Click Finish button and I'm left with a blank blue screen. Not a BSOD. It's Windows with Explorer running. Can manually run it with Task Manager. Then I can't access start menu. Spinning circle over button and task bar.

If I wait for the first message then manually close Explorer out, install, then re-run Explorer after setup, then the install works fine and it runs fine afterwards. Can probably reproduce this 10/10 times in a VM. Just did it 3 times in a row.

**Comment by 488GTB** [comment] 2018-08-24 10:48
Yes. I also had the same problem with 4.4.129 and 4.4.130.

Regards

**Comment by ge0rdi** [comment] 2018-08-29 10:01
I can replicate the same issue with original `ClassicShell` too. So it doesn't seem to be related to `OpenShell` changes (there were just minor cosmetic changes in the installer).

Though, definitely it will be great to fix it somehow.

I'll try to play with it a bit. In worst case add explicit _explorer.exe_ termination and restart.
But this should be really a job of MSI installer. And usually it does the job, but it seems there is some issue that prevents it from successful _explorer_ termination. So I'd like to investigate this.

**Comment by thunderpants** [comment] 2018-08-29 19:48
I just installed OpenShellSetup_4_4_131.exe on 1803(fully updated) ,no problems ,installed ok.
Explorer shut down ok until it was finished.

**Comment by AveYo** [comment] 2018-08-29 21:02
@thunderpants: the issue is not about when it works, it's about when it fails - and it fails consistently at least 2 out of 10 times in the following scenario: _"upgrading from the classic / previous versions"_  i.e. having ClassicShell / OpenShell already running.

**Comment by ibuprophen1** [comment] 2018-08-30 00:00
So the issue is that the installer doesn't/can't stop the Classic Shell before upgrading the software to Classic Start which, in turn, isn't able to restart the explorer.exe because Classic Shell is still running.

This is probably resulting in an incomplete upgrade to the Classic Start because of one or more of the Classic Shell dependencies still running. 

I hope I had explained this okay via text... 👍


~Ibuprophen

**Comment by Hadden89** [comment] 2018-09-13 23:41
I've seen this behaviour in several MSI installers. So worth forcing a terminate-and-restart explorer in the setup ;)

**Comment by XenHat** [comment] 2018-09-28 14:32
Looks fixed to me. Just installed it on a clean Windows install
![image](https://user-images.githubusercontent.com/980408/46214760-a6bace00-c2f0-11e8-9200-0c3d73ac2426.png)

**Comment by ibuprophen1** [comment] 2019-05-29 22:22
It looks like this issue has been resolved... 

I'm going to close this issue then. 👌 


~Ibuprophen

**Closed by ibuprophen1** 2019-05-29 22:22 UTC
