### ISSUE TITLE
Openshell sometimes crashes (and doesn't completely restore systray on restart) if using the search

### ISSUE THREAD

**Issue by jesses408** [Open-Shell/Open-Shell-Menu#1263] opened 2022-12-26 16:06 UTC
**Describe the bug**
Refiling bug #1147 . I tried upgrading to version 4.4.178 as suggested and the problem seemed to go away. Today I tried using the search bar to search for a program I installed a few days ago, and as soon as I start typing into the search box, the application crashed. It also still doesn't restore the systray to the previous state - a bunch of the icons are always missing after it restarts. 

**To Reproduce**
Click start button
Start typing a few letters in search
Openshell crashes

**Expected behavior**
Openshell does not crash on search
If crashing, when restarting itself, it should bring itself to a fully working state

**Screenshots**

**Version:**
 - Open-Shell: 4.4.178
 - OS: Windows 11 pro for workstations, version 22H2, OS build 22621.963

**Comment by ge0rdi** [comment] 2022-12-26 17:03
There was no need to create new issue. You could have provided requested info to the old one (so that we have all the context).

Anyways, you were asked to provide dump from the crash. Without it we cannot help you.
If you are able to reproduce the crash then please create dump using this [guide](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-create-dump-on-Windows-Explorer-crash).

If the crashing is random and you cannot reliably reproduce it, you can instruct WER to store dumps from explorer using these steps:

- Run `regedit.exe` as elevated admin
- Create `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\explorer.exe` key
- In the key create DWORD `DumpType` and set value `2` to it (to create full dumps)
- Then wait for the crash
- The dump should be created in `%LOCALAPPDATA%\CrashDumps` folder

**Comment by jesses408** [comment] 2022-12-26 22:19
Hi, I didn't see a way to reopen the other bug. Today I updated the openshell version to latest and make the registry change to store the dump for the next time it crashes

**Comment by jesses408** [comment] 2022-12-26 22:20
Also, can we also address separately the issue that if openshell launches at any other time than system startup, the systray ends up with half the icons missing?

**Comment by ge0rdi** [comment] 2022-12-27 07:26
> I didn't see a way to reopen the other bug

It should be still possible to add comments to closed issue.
We can reopen it if relevant info is added.

> for example after crashing and restarting, or if upgrading the version

If explorer crashes or is restarted (for example after `Open-Shell` installation) then it may happen that some icons on task bar will get missing. For example Explorer windows that were previously opened. Its just how Explorer works.

Though if you have some other programs running then those should show their icons once Explorer is restarted.

**Comment by jesses408** [comment] 2022-12-27 14:24
Hi, I'm referring to the system tray only (near the clock), not the entire task bar

> > for example after crashing and restarting, or if upgrading the version
> 
> If explorer crashes or is restarted (for example after `Open-Shell` installation) then it may happen that some icons on task bar will get missing. For example Explorer windows that were previously opened. Its just how Explorer works.

**Comment by ge0rdi** [comment] 2023-01-15 09:44
I will close this for now.
If you'll be able to gather some crash dumps, please attach it here and we can reopen.

**Closed by ge0rdi** 2023-01-15 09:44 UTC

**Comment by jesses408** [comment] 2023-01-16 17:08
It crashed today when I typed 1 letter into the search box

**Comment by jesses408** [comment] 2023-01-16 17:10
It did not produce a crash dump in %LOCALAPPDATA%\CrashDumps

**Comment by jesses408** [comment] 2023-01-16 17:12
[crash.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/10427935/crash.zip)
Crash dump

**Comment by jesses408** [comment] 2023-01-16 18:32
Now that I think of it, I hear the DING noise right before it crashes (after I type the first letter). The noise I hear corresponds to several different windows events such as "Asterisk, Default Beep, Exclamation", in other words it's a sound that it plays when something goes wrong. So not sure if this is a cause or effect

**Comment by jesses408** [comment] 2023-02-15 18:28
Hi, where did we leave off here? The explorer continues to crash at random when typing even a single character into the search field. I can't find any pattern to it. Can you give me a debug build that has more logging, or can you put some additional logging into the next version that can give some clues as to why it's crashing?

**Comment by ge0rdi** [comment] 2023-02-15 18:50
I wrote that it crashes in `Realtek` control panel module.
So you should try to uninstall it (`Realtek HD Audio Sound Effect Manager` ?) or install latest drivers for your sound card.

Did you try any of that?

**Comment by jesses408** [comment] 2023-02-15 21:30
Hi, how is the sound driver making explorer crash? And if something was wrong with the sound drivers, wouldn't things in Windows be crashing left and right all day long and not just explorer? If something is wrong with the sound driver, wouldn't the sound driver itself be crashing?

**Comment by ge0rdi** [comment] 2023-02-16 05:58
Not sound driver is making explorer crash, but rather control panel module that is most likely part of sound drivers.
That's why I recommended to try to update your sound drivers to latest version to see if the issue persists.

Eventually try to look for `Realtek HD Audio Sound Effect Manager` (or anything Realtek related) in `Apps & Features` and uninstall it to see if it will make any difference.

**Comment by jesses408** [comment] 2023-02-16 12:51
This is a new Dell Precision 5820 that came with Windows 11. All drivers are already up to date. There is no newer Realtek driver than what's installed. There is nothing in the control panel with the word "realtek" in it. To see it, I have to go into system, device manager, sound video and game controllers, and in there is "Realtek Audio". I don't see why the classic shell would be enumerating the sound video and game controllers section of the device manager

**Comment by jesses408** [comment] 2023-02-16 15:23
Also even if there was something wrong with the Realtek audio driver, simply looking at it in the control panel or in the list of apps should not cause the explorer to crash. The driver itself is not involved in the process of looking at it in the control panel. The driver would only be involved if playing a sound through the sound device

**Comment by ge0rdi** [comment] 2023-02-16 17:42
I will repeat once again that I'm not talking about audio driver.
The crash happens in `RTSnMg64.cpl` that looks like _control panel_ extension module by Realtek.
`Open-Shell` seems to be enumerating _control panel_ items at that moment, so it all fits together.

You can try to locate and disable that CPL module using [Autoruns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns) tool.
Run it as administrator and search for `RTSnMg64` (using Quick filter).
Then disable it by unticking the checkbox near it, restart machine and then check if those crashes do still happen.

**Comment by l1m3r** [comment] 2025-05-02 01:49
A little OT - but since I very rarely suffer the same problem, **here's a way to restore most if not all tray icons**: https://stackoverflow.com/a/15555605/4323903 (ther's an executable download there - [here's the source](https://github.com/ringmaster/trayrestore))
