### ISSUE TITLE
"Align to Corner" fails.

### ISSUE THREAD

**Issue by enderdesign** [Open-Shell/Open-Shell-Menu#1673] opened 2023-08-19 01:20 UTC
### Describe the bug

Align to corner of the screen checkbox doesn't do anything.

### Area of issue

Taskbar

### To reproduce

Settings / Start Button / check "Align to Corner"

### Expected behavior

Open shell start button aligned to left corner

### Open-Shell version

4.4.190

### Windows version

win 11 build 22000 and 22621

### Additional context

Interestingly, it worked fine in win 11 for version .170
Previously, I kept Open-shell to the left corner like a win 7 menu while leaving the win 11 start menu active.  Best of both worlds.
Now, the "replace" overlays the win 11 and the align to corner functionality is lost.
Tested on win 11 Enterprise and Home.  build 22621 and 22000 respectively

**Comment by ge0rdi** [comment] 2023-08-19 06:29
You can see discussion #1252 regarding start button position.
In short, previous `Open-Shell` versions didn't support Windows11 correctly and the button/menu was on the left side by mistake.

> Align to corner of the screen checkbox doesn't do anything.

It does, but not what you think.
The option is not meant to place start button to the corner of the screen even if should be in the middle (when left taskbar alignment is used).

Normally (without the checkbox) we try to place custom start button image in the middle of taskbar vertically. Here is how it looks like:
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/2453094/bd336817-fac5-4700-8e05-1e26e5098918)

With `Align to corner of the screen` enabled we align to button to _corner_ of the screen (that is bottom in case of bottom taskbar placement) and thus custom image may extend from taskbar more:
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/2453094/e60bb7d3-8a45-42a9-8b04-6d68a0e3a783)

The effect is rather subtle and it is usually _wanted_ for bigger buttons that should overhang from taskbar. For smaller images that fit into taskbar is usually better to center them vertically.

So the setting works as intended/designed.

**Comment by ge0rdi** [comment] 2023-08-24 09:48
I have renamed the setting to `Align to edge of taskbar` so that it is more clear what it is supposed to do (422b048).

I'm closing this as the setting works as intended.

**Closed by ge0rdi** 2023-08-24 09:48 UTC
Labels: Bug
