### ISSUE TITLE
EXACTLY WHY I HATE WINDOWS 11

### ISSUE THREAD

**Issue by WindowsFailed11** [Open-Shell/Open-Shell-Menu#1888] opened 2024-03-30 12:34 UTC
### Describe the bug

So, when I use a custom start button. The custom one displays over the original one and I can still see the Windows 11 start button and it pisses me off!!!!! 4/20

### Area of issue

Taskbar

### To reproduce

![Screenshot 2024-03-30 083237](https://github.com/Open-Shell/Open-Shell-Menu/assets/165480178/c125e605-a253-479d-898b-92d58cde9575)

### Open-Shell version

4.4.191

### Windows version

Windows 11 22H2

### Additional context

![Screenshot 2024-03-23 142117](https://github.com/Open-Shell/Open-Shell-Menu/assets/165480178/da085c81-60cf-4f97-8523-62de9ec55434)

**Comment by ge0rdi** [comment] 2024-03-30 16:33
Duplicate of #1631.

**Closed by ge0rdi** 2024-03-30 16:33 UTC
Labels: Bug
