### ISSUE TITLE
Taskbar customization not working with latest windows 11 update 

### ISSUE THREAD

**Issue by GagaBlagBlag** [Open-Shell/Open-Shell-Menu#1511] opened 2023-03-22 02:24 UTC
### Describe the bug

Taskbar customization changes made do not have any impact on operating system. This issue began once latest windows 11 22H2 22621.1413 update was applied. Issue is in both most recent stable and nightly builds.

### Area of issue

Taskbar

### To reproduce

1. Install most recent Windows 11 update
2. Open Open-Shell
3. Turn on Taskbar Customization
4. Apply any change

### Expected behavior

My custom taskbar texture to apply.

### Open-Shell version

4.4.189

### Windows version

windows 11 22H2 22621.1413

**Comment by daknut** [comment] 2023-03-22 08:47
This seems to be a duplicate of the bug reported on https://github.com/Open-Shell/Open-Shell-Menu/issues/1342

**Comment by ge0rdi** [comment] 2023-03-22 09:02
Yup, this was already reported.

**Closed by ge0rdi** 2023-03-22 09:02 UTC
Labels: Bug
