### ISSUE TITLE
Search not work good

### ISSUE THREAD

**Issue by Telrik** [Open-Shell/Open-Shell-Menu#325] opened 2020-02-25 18:16 UTC
Sorry if it's already posted. but most annoying thing about open shell is search
here i try to search for windows update menu..
https://i.imgur.com/Kov0JVv.png and nothing
so every time i need to switch to original windows menu and use it's search
https://i.imgur.com/b6Vy1Vj.png and here it is ...

**Comment by ge0rdi** [comment] 2020-02-25 18:55
This is known issue.

Duplicate of #57

**Closed by ge0rdi** 2020-02-25 18:55 UTC
