### ISSUE TITLE
Even if you select Japanese, it will not be reflected

### ISSUE THREAD

**Issue by Hayao0819** [Open-Shell/Open-Shell-Menu#46] opened 2018-07-20 04:35 UTC
言語設定から日本語を選択しても反映されません
改善よろしくおねがいします

**Comment by ibuprophen1** [comment] 2018-07-20 13:18
@shun819, your issue roughly translated to English... 

Even if you select Japanese from the language setting, it will not be reflected
Thank you for your improvement. 


~Ibuprophen

**Comment by Rukoto** [comment] 2018-07-20 17:18
He recognizes that Japanese translation is not applied in the setting window as a bug.
However, he does not seem to understand the mechanism of translation.

@shun819
Classic Start is normally displayed in Japanese except for the setting window.
You need to understand the localization mechanism by reading
"Classic-Start/ClassicStartLoc/English/Localization.rtf".

The current Classic Start does not include the DLL file necessary for translating 
and displaying the setting window.
Also, distribution of language files (ja-JP.dll etc.) is not done.
This is the current Classic Start specification and is not a bug.

If you want to display the Classic Start setting window in Japanese immediately, 
you can use ja-JP.dll of Classic Shell.

Well, do you have a good idea on the localization of Classic Start?
(How to manage text-based instead of DLL file, etc.)
If not, this issue should be closed.

**Comment by ibuprophen1** [comment] 2018-07-20 20:00
It seems as though this may be a "Dialect" issue... 

I've seen a similar issue somewhere for another Github project. I'm going by memory here... Because of different Dialects, primarily, regarding the Chinese language. 

I'm doing my best here... LMAO!

This issue might be because of the Japanese language has 7 primary Dialects and, the same as the other project, the Japanese language may need to be examined a bit further for those distinctions. 

How did I do with explaining this okay via text and memory... 😵


~Ibuprophen

**Comment by shun819** [comment] 2018-07-21 01:31
ありがとうございます
メールの送信後、JA-JP.dllを導入させることによって日本語にすることができました
しかし、このJA-JP.dllはClassicShell時代のものであり、更新も停止してしまっています
公式から配布することはできないでしょうか？
私は、Windows10のたくさんのアップデートに対応させるのが大変なことを知っています
もし難しいようであれば翻訳ファイルの作成方法を教えてくれれば自分で配布します
よろしくおねがいします

**Comment by Rukoto** [comment] 2018-07-21 03:17
@shun819 You do not seem to understand the situation at all.
Classic Start is still under discussion of localization and is about to reconstruct from that method in order to ensure safe and high quality localization for everyone in the world.
I feel sorry that its progress is not good, but if you can not help this project, you are just a creamer.

How you created and distributed files such as ja-JP.dll you will need to investigate yourself before you ask passionate-coder members.
In the first place you are not tracking "Localization.rtf" I presented and related topics in this repository properly. ex: #8

GitHub is an open source community. You need to study again from that way of involvement.
And people around the world are watching your behavior. I am ashamed as the same Japanese.
Please do not annoy us with your noise. I hope that this issue will be closed promptly.

-日本語訳-
@shun819 あなたは全く状況を理解していないようです。
Classic Startはまだローカリゼーションの議論が浅く、世界中の皆が安全で品質の高いローカライズがされるために、その手法から再構築を行おうとしている段階です。
その進捗が芳しくない事は私も残念に感じているが、あなたがこのプロジェクトに助力できないのであれば、あなたはただのクレーマーでしかありません。

ja-JP.dll等のファイルがどのように作成され配布されてきたかはpassionate-coderのメンバーに聞く以前に自身で調べる必要があるでしょう。
そもそもあなたは、先に私が提示した"Localization.rtf"や、このレポジトリ内の関連トピックをちゃんと追跡していない。例えば #8

GitHubはオープンソースコミュニティです。その関わり方からあなたは勉強し直す必要があります。
しかも世界中の人があなたの振る舞いを見ている。私は同じ日本人として恥ずかしい思いをしている。
あなたのノイズで皆を困らせないで下さい。すみやかにこのissueが閉じられることを願います。

**Comment by ibuprophen1** [comment] 2018-07-22 18:03
Rough Translation of the last message from @shun819... 

"Thank you. After sending the email, I was able to put it into Japanese by introducing JA - JP.dll However, this JA - JP.dll was in the ClassicShell era and the update was also stopped Can you distribute it from official? I know that it is hard to adapt to many updates of Windows 10. If it seems to be difficult, distribute it by yourself if you tell me how to create a translation file."


~Ibuprophen

**Comment by coddec** [comment] 2018-07-23 00:44
What about including the DLLs by default within the installation file?
@XenHat @ge0rdi 
Thoughts?
Will it be easier for users to switch language?

**Comment by Rukoto** [comment] 2018-07-23 03:20
@coddec 
If it is difficult to include a DLL in the installer or repository, how about adding a link to README.md?
There is a problem that includes the keyword "Classic Shell", but I think that you can fix it later.
You should also include the DLL installation destination.
"C:\ProgramData\ClassicStart\Languages"

Of course, although discussion is necessary about future DLL renewal methods...

**Comment by ibuprophen1** [comment] 2018-07-23 17:04
@coddec, I remember asking about that similar question a while ago and, wouldn't you know it, i can't locate my question... LMAO! 

I had asked about extracting the language information from the dll and creating separate ones with individual dll files for each language and this was considered as unnecessary. 

Maybe another idea is to create a type of language pack with English and others as the primary and a language pack with the additional languages. 

Just a thought... :-) 


~Ibuprophen

**Comment by XenHat** [comment] 2018-07-23 23:30
As I have already outlined in my [Localization Instructions](https://github.com/passionate-coder/Classic-Start/wiki/Localization-instructions), **the DLL files are only used to __override__ the built-in translation.**
Every missing translation **should be added to the source code**, and DLL only used **to perform customized (Themed) translations.

**Comment by coddec** [comment] 2018-07-24 01:16
@XenHat Sorry 😂 my fault
I can recall that now 🤦‍♂️

**Comment by ibuprophen1** [comment] 2018-07-24 03:07
@XenHat, rodger wolco! 😇

**Comment by Rukoto** [comment] 2018-07-24 07:56
@coddec @XenHat @ge0rdi 
It should not be allowed to distribute DLLs that can not be ascertained as safe.
However, was not anyone wanting to delete the assets of the translation?
DLLs are deleted from this repository, and it seems that many translations are lost.

The attached file converts all DLLs to text base and edits it.
These files have been merged based on the resources of Classic Start Version 4.4.101 
and are made to be usable immediately by converting them to DLL files.
Can you save these files under the "ClassicStartLoc" directory? (Except English)

I tried doing what I can do.
Please consider the inheritance of translation assets.
[Languages.zip](https://github.com/passionate-coder/Classic-Start/files/2222569/Languages.zip)

**Comment by ge0rdi** [comment] 2018-07-28 17:02
I think it will be better to ask Ivo for original source files for language translation DLLs.
We could include them in repo then.

@coddec Could you ask him to get those files?

**Comment by coddec** [comment] 2018-07-29 03:09
Email I've sent:
>Hi Ivo,
>
>Sorry for disturbing.
Community contributors are trying to contribute to language translation, but it seems they need original source files for language translation DLLs.
https://github.com/NeoClassic-UI/Menu/issues/46#issuecomment-408621438
Is it ok for you to share with us and the community?
>
>Thank you very much!
>Regards,
>coddec


<br>

Reply from Ivo:
>I am not sure what you are asking for. However
First, the DLLs are the source. You can use a registry editor for them. The ClassicShellUtility project has some ability to extract and import text to DLLs, but it is a convenience feature, not strictly necessary.
But more importantly, the existing localization DLLs were done by volunteers, which have not explicitly agreed to share their work. That’s why the DLLs are not part of the distribution. They can be downloaded from the Classic Shell website.

**Comment by ge0rdi** [comment] 2018-07-29 07:42
So I guess we cannot use those translations without getting consent from original authors :(

We may ask Ivo for their contacts (if he's willing to share) and ask them if we can use their translations.
Or we'll simply wait until some of them (or someone else) will contribute them to this project.

**Comment by Rukoto** [comment] 2018-08-01 08:51
@coddec I tracked the original author as much as possible.
Although it is obtained from published information, it may not be a good feeling.
If you do not want to contact like this, I will delete the file.
[Contributors.csv.txt](https://github.com/NeoClassic-UI/Menu/files/2248693/Contributors.csv.txt)

**Comment by ibuprophen1** [comment] 2019-05-29 22:38
It's been almost a year since @Hayao0819 had last followed up on this issue... 

I'm going to close this as being resolved (in one fashion or another) and the Developer(s) are aware of this now. 


~Ibuprophen

**Closed by ibuprophen1** 2019-05-29 22:38 UTC
