### ISSUE TITLE
System Settings Button Doesn't Work 1809

### ISSUE THREAD

**Issue by s-crypt** [Open-Shell/Open-Shell-Menu#154] opened 2019-03-13 18:24 UTC
Ever since I upgraded to Windows 1809, the **system settings** button on the windows 7 style menu does not work. The button does not do anything when clicked.
Edit: Clarified system settings, **not** Open-Shell Menu settings

**Comment by beren12** [comment] 2019-04-25 19:21
It works fine on 3 machines here.

**Comment by AveYo** [comment] 2019-04-26 08:15
You can create a custom button with command `ms-settings:`  
Could also try my [Optimized Settings profile xml](https://gist.github.com/AveYo/f2add193abfb2ddc5963e11273df083b)  
_import via Programs - Classic Shell - Classic Start Menu Settings - Backup - Load from XML file.._

**Comment by MartinX3** [comment] 2019-04-28 15:06
I can reproduce the issue.

Now I need to do a "double click" instead of a normal click to open the system settings / system control.

**Comment by cryppt** [comment] 2019-04-28 16:01
My issue was resolved via @AveYo, the url scheme was broken, but it looks like there is another issue with @MartinX3.

**Closed** 2020-08-31 20:13 UTC
