### ISSUE TITLE
Horizontal Position Offset not working after newest update

### ISSUE THREAD

**Issue by RustedEmber** [Open-Shell/Open-Shell-Menu#1629] opened 2023-07-28 22:06 UTC
### Describe the bug

I used to be able to type a negative number to move the whole start menu to the left off screen, but it no longer does this. Now it only registers 0 and higher positions.

### Area of issue

Start menu

### To reproduce

1. Go to settings
2. Search for horizontal
3. Modify the horizontal offset to a negative number, ex: -10.
4. You see that the start menu behaves as if you put a 0 in the field.

### Expected behavior

The start menu to move to the left with negative numbers.

### Open-Shell version

4.4_190

### Windows version

Windows 10 22H2

**Comment by ge0rdi** [comment] 2023-07-29 07:10
> I used to be able to type a negative number to move the whole start menu to the left off screen

So you want to like _hide_ part of the start menu (put it off screen)?
Wondering what's the purpose of that.

> Now it only registers 0 and higher positions.

I can confirm. And I see where the _problem_ is (part of changes due to Windows 11 center aligned taskbar support).

**Comment by jfgimenezx** [comment] 2023-07-30 11:56
Hi,
I have the same problem. It always left a margin of 9 pixels.
It did so before, but I had a value of -8 in "Horizontal position offset" and worked fine. Now it doesn't accept negative values  :-(

![imagen](https://github.com/Open-Shell/Open-Shell-Menu/assets/62906351/f2590a2c-1035-463a-9f30-88608f69baa1)

![imagen](https://github.com/Open-Shell/Open-Shell-Menu/assets/62906351/fd162ed0-c65c-4295-b074-026b45fce265)

**Comment by ge0rdi** [comment] 2023-07-30 16:33
@jfgimenezx 
What version of `Open-Shell` do you use?
Does the same happen with some of _standard_ skins (like `Metro` or `Immersive`)?

**Comment by jfgimenezx** [comment] 2023-07-30 17:26
1) 4.4.190
2) Other skins haven't show that margin (it seems an issue for "Fluent-Metro"), but negative values are not allowed too. ITOH, vertical position does accept any value, including negative ones:
![imagen](https://github.com/Open-Shell/Open-Shell-Menu/assets/62906351/3338cb43-24ee-44bb-841c-ea8dc2cd96ec)
![imagen](https://github.com/Open-Shell/Open-Shell-Menu/assets/62906351/312a0965-fb20-490a-86b2-14ba23fc414c)

**Comment by ge0rdi** [comment] 2023-07-30 17:41
> it seems an issue for "Fluent-Metro"

It seems to be caused by `Menu border style` set to `Floating` (in `Fluent-Metro` skin settings).
That one adds some vertical/horizontal offset to the menu.

You can eventually set it to `Classic` as a workaround.

> vertical position does accept any value, including negative ones

There is similar problem for vertical offset, but it gets visible with vertical taskbar.

I'm looking into this and trying to figure out how to fix it.
Negative offsets are supposed to work, so current behavior is a bug.

**Comment by jfgimenez** [comment] 2023-07-30 18:22
Thank you very much!

**Comment by ge0rdi** [comment] 2023-07-31 12:31
Guys, you can try with fixed build from #1636 PR.

**Comment by jfgimenez** [comment] 2023-07-31 16:37
> Guys, you can try with fixed build from #1636 PR.

Now it works fine!

![imagen](https://github.com/Open-Shell/Open-Shell-Menu/assets/3890011/c42d418b-52d0-4152-9a24-16f7dbecb98f)

![imagen](https://github.com/Open-Shell/Open-Shell-Menu/assets/3890011/809b2234-86e4-4a8c-9c4a-3ba9bce82018)

Thank you very much!

**Comment by ge0rdi** [comment] 2023-08-23 07:30
Fixed in `4.4.191`.

**Closed by ge0rdi** 2023-08-23 07:30 UTC
Labels: Bug
