### ISSUE TITLE
On Update (or Repair) I get Warning 1946 

### ISSUE THREAD

**Issue by habakuk007** [Open-Shell/Open-Shell-Menu#2020] opened 2024-11-07 12:30 UTC
### Describe the bug

I get this warning if I install the current update (or use the repair function):

> "Warning 1946. Property '{9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3|, 26' for shortcut 'Open-Shell Update.lnk' could not be set." and
> "Warning 1946. Property 'System.AppUserModel.ID' for shortcut 'Classic Explorer Settings.lnk' could not be set.".

Same as https://github.com/Open-Shell/Open-Shell-Menu/issues/1575 

### Area of issue

Installation/Other

### To reproduce

Call `.\OpenShellSetup_4_4_191.exe /lvx* install.txt`
Installation works, but warning is shown.

### Expected behavior

No warning

### Open-Shell version

4.4.191

### Windows version

Windows 10 22H2

### Additional context

Log: 
[install.txt](https://github.com/user-attachments/files/17661471/install.txt)

**Comment by ge0rdi** [comment] 2024-11-07 20:21
This is duplicate of #1672. 
Check that one for more info (though it is not clear what causes the issue).
Lets just keep it there.

**Closed** 2024-12-13 11:08 UTC
Labels: Bug
