### ISSUE TITLE
Conflicting with Windows Blinds skinning

### ISSUE THREAD

**Issue by Braxusz** [Open-Shell/Open-Shell-Menu#433] opened 2020-08-29 04:51 UTC
**Describe the bug**
When Open-Shell is used in conjunction with Windows Blinds, the taskbar is skinned in black/grey and not the colors of the WindowsBlinds skin

**To Reproduce**
1. Apply a skin
2. Taskbar coloring breaks
3. Exit Open-Shell, goes back to normal with proper skinning.

**Expected behavior**
To not have the taskbar affected, 

**Screenshots**
With Open-Shell enabled
![WithOpen-Shell](https://user-images.githubusercontent.com/70422288/91628767-ec1e2500-e977-11ea-90a1-3a569c6f06d2.jpg)
Without Open-Shell enabled.
![WithoutOpen-Shell](https://user-images.githubusercontent.com/70422288/91628768-ecb6bb80-e977-11ea-9235-842ae0aedf71.jpg)

**Version:**
 - Open-Shell: [e.g. 4.4.1.42]
 - OS: [e.g. Windows 10 2004]

**Comment by ge0rdi** [comment] 2020-08-29 11:47
Try to disable Taskbar customization in `Open-Shell settings` -> `Taskbar` -> `Customize taskbar`.

**Comment by blackwidowfarms** [comment] 2020-08-29 19:08
I am having the same issue... no change disabling Taskbar. It would be awesome to have the best of both worlds... OpenShell Start Menu and the XP explorer buttons from windowblinds :)

**Comment by ge0rdi** [comment] 2020-08-30 18:53
@blackwidowfarms 
> no change disabling Taskbar

So you have disabled `Customize taskbar` and the issue is still there, right?
Can you check if it goes away when you _exit_ `Open-Shell` menu (right-click on start menu and select `Exit`)? 

And then when you start `Open-Shell` again, issue will reappear, right?

**Comment by Braxusz** [comment] 2020-08-30 21:58
that is correct, when you exit from the menu it goes back to normal, and
then if you open it again it goes back to broken.

**Comment by blackwidowfarms** [comment] 2020-08-31 07:49
yes correct

**Comment by DerellLicht** [comment] 2020-09-03 18:11
Yes, this has been a problem for quite some time now.  I tried discussing it on the discussion forum, but never got any replies.
It would be *very* lovely to have this problem solved; I truly love both WB and ClassicShell, but if I have to choose *one*, especially for Windows 10, it will have to be WindowBlinds.

**Comment by blackcrack** [comment] 2020-09-23 06:26
why not implementing support for window blinds skins .. other code, same effect, but a Checkbox for :   
Stertmenu-> Right Click, Configuration
=> Taskbar
* [X] Customized taskbar
*  [X] Support for Windows Blinds 
* [ ] Taskbar appearance

**Comment by bonzibudd** [comment] 2020-10-16 01:53
I can confirm this with a 30 day trial of WindowBlinds.

I have just found a forum post that seems to suggest that the issue was caused by Classic Shell 4.3.0: [http://www.classicshell.net/forum/viewtopic.php?f=12&t=7370](http://www.classicshell.net/forum/viewtopic.php?f=12&t=7370)

It must be something to do with the Taskbar settings introduced in that version. However I don't know why it would break it even with the setting disabled. I'll poke around and see if I can make anything work.

**Comment by DerellLicht** [comment] 2020-10-16 02:10
> I can confirm this with a 30 day trial of WindowBlinds.
> 
> I have just found a forum post that seems to suggest that the issue was caused by Classic Shell 4.3.0: http://www.classicshell.net/forum/viewtopic.php?f=12&t=7370
> 
> It must be something to do with the Taskbar settings introduced in that version. However I don't know why it would break it even with the setting disabled. I'll poke around and see if I can make anything work.

The issue is present with Open Shell as well, even if Classic Shell is not installed.  It has also been present in all three most recent versions of Open Shell.

Sadly, Stardock (maker of WindowBlinds) has absolutely *no* interest in trying to address this issue, since they have their own (not free) Start Menu replacement program that they want to sell.  So either we will have to resolve it, or choose between WB or OS...

**Comment by blackcrack** [comment] 2020-10-16 05:11
if he want not work together with the community, can he also .... .... and .... the community, 
why should we support him.. A open and free community this Guy with his issues at Open-Shell
and by the way.. it's the successor of Classic shell... so what.. 

He should look to make his Program as open Source and give it free as GPL2 Software to be it possible to work together .. so should we have also not a issues, he have a issue for working together and fix his program ... because he want sell it .. not visa versa..

**Comment by blackwidowfarms** [comment] 2020-10-16 05:17
I 
don't think insulting people is the solution lol but it would be great to have say, access to the potential area the WB conflict is in, so we could mess with it and compile ourselves? guidance that way would be most appreciated, I'm 
appreciative of how they have time to interact with us little guys at all. 





----- Original Message -----

**Comment by blackcrack** [comment] 2020-10-16 05:22
" be friednly, hopeful and be nice " so, what ?
i have easy forgotten to put in.. 
and oh,

peoples want become personally and you want going on me  ?
to close this issue is maybe recommended ..

**Comment by DerellLicht** [comment] 2020-10-16 05:24
Well, I don't entirely understand whatever @blackcrack is talking about, but we're on the Github page for this product, so clearly it is open source... however - it is very complex, and few really understand the internals of the program... plus, there is the problem of the constantly changing, undocumented internals of Windows 10, which is the reason that the original Classic Shell abandoned the project after so many years.

In any case, however, I *don't* agree with closing this issue; a number of us would desire very much to have it resolved !!  I don't know, though, just how many active developers the project has  at this point...

**Comment by blackcrack** [comment] 2020-10-16 05:30
you have no right to solve a commercial program problem with an open source problem.
You can report a problem, but whether it is solved by programmers who are only helping and not being paid here, I'm sure others will also want to help if they want it to be fixed.

So, want it be fixed, fix it by self make it like @ge0rdi told

> Try to disable Taskbar customization in `Open-Shell settings` -> `Taskbar` -> `Customize taskbar`.

or find a programmer who want fix it ..

**Comment by blackwidowfarms** [comment] 2020-10-16 06:47
Solving commercial program problems with open source is what open source is 
for. It can be altered to accommodate conflicts with those commercial programs. 
The very idea of skinning is about getting around roadblocks to those ends. Not 
sure who blackcrack is but sounds like a developer.?

 Blaming us and the commercial program seems like pride to me, as does 
regurgitating an old solution which does not work, I am no longer asking for a 
solution because I can accept that "the programmer simply cannot do it" but is 
too proud to admit it or solve it?

 I thought this was a project of passion for you guys, do you hate your own 
creation enough to be rude to us? Then take it down lol problem solved.





----- Original Message -----

**Comment by ge0rdi** [comment] 2020-10-16 06:55
@blackcrack 
There is really no point to comment like this.
If you can't provide reasonable advice that will help people with their problem then please rather don't comment on it.

This is issue tracker for `Open-Shell` so if people have some problem when using `Open-Shell` they should be encouraged to report it here.
It is up to maintainers of the project to decide what should stay opened and what not.

At this point it is not clear where the _clash_ between Windows Blinds and Open-Shell lies.

And even if it was clear there is no need to accuse anybody for anything. WB has their own software and they are not obliged to make it compatible with every other software that users can run.

Eventually someone may figure out where the problem is (Open-Shell is open source so anyone can compile/debug it).
And based on that finding we may decide what to do with it (fix a bug in OS, do a workaround, do nothing).

@blackwidowfarms 
>  I thought this was a project of passion for you guys, do you hate your own
creation enough to be rude to us? Then take it down lol problem solved.

Please, calm down too. @blackcrack is not member of `Open-Shell` team, so there is no need to think his opinions are the same as those of team's.

We are all working on this project in our spare time, so please don't expect that everything will be fixed (right away).

**Comment by blackwidowfarms** [comment] 2020-10-16 18:13
thanks very much :) sorry about my rude response, and besides... you guys work 
very hard at these things and I think not enough credit is given to you for 
that. I applaud your efforts to keep your program working and  I will continue 
to recommend openshell to people because its simply awesome.

  
It's something which stays the same, regardless of where the corporate realm takes Windows. Decades from now your software will still be around, chugging away on stashed "non cloud" machines that we the freedom-loving people of the world will refuse to give up in a time of centralization and globalization. 


----- Original Message -----

**Comment by ge0rdi** [comment] 2020-10-18 07:27
I was able to pinpoint the issue. Will submit PR with workaround soon.

Here is some technical info:

`Open-Shell` hooks `SHFillRectClr` (ordinal 197) API from `shlwapi.dll` in order to be able to customize taskbar.
The API is hooked even if taskbar customization is disabled in `Open-Shell` (default).

`WindowBlinds` hooks the same API so this is causing clashes between both programs.
In fact `Open-Shell` hooks later which makes `WindowBlinds` hook to be completely ignored.

The solution would be to hook only if taskbar customization is enabled.

This way `Open-Shell` should be more compatible with other customization
tools in default state.

**Comment by blackwidowfarms** [comment] 2020-10-18 07:42
that's beautiful! what a great find, congratulations on that sir! :D


----- Original Message -----

**Comment by Braxusz** [comment] 2020-10-19 02:32
Nice work, thanks for this. I look forward to testing it out!

**Closed** 2020-10-23 08:14 UTC
Labels: Acknowledged/Being Looked Into by Dev's

**Comment by blackwidowfarms** [comment] 2020-10-23 08:47
It totally works, like a charm! no more conflict with windowblinds. Thanks very 
much geOrdi, unhooking it worked.





----- Original Message -----

**Comment by ge0rdi** [comment] 2020-10-23 09:04
@blackwidowfarms 
Cool. Thanks for confirmation 👍

**Comment by bonzibudd** [comment] 2020-12-29 00:15
@ge0rdi 

I have been using builds with this change for a while, and I think there is a problem associated with it.

It seems that in some cases, when you first enable taskbar customization and change something like the taskbar texture, only the area around the Start button and tray area will immediately update. For the entire Taskbar to update, you need to exit the StartMenu process and reload. I have seen this happen on both Windows 7 and 10. 

![image](https://user-images.githubusercontent.com/61938331/103250232-e8f46f00-4940-11eb-94c8-d17b68eadbf2.png)

**Comment by ge0rdi** [comment] 2020-12-29 09:01
Yes.

Open-Shell has to be restarted after taskbar customization was enabled,
After restart it will hook all required things, so customization will work well.

I guess we can add some notification about required restart. Feel free to create new issue for that.

**Comment by DerellLicht** [comment] 2021-01-02 18:31
@ge0rdi ;
What version of Open Shell is this implemented in?  I just downloaded and installed V 4.4.160, but it still has this conflict with WindowBlinds.  I tried restarting the machine, but that did not fix it.  Do I need a beta build or something??

**Comment by blackwidowfarms** [comment] 2021-01-02 20:29
it's right here, derell: https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts
it's 
version 4.4.162 just make sure to disable taskbar customization in openshell 
options :)



----- Original Message -----

**Comment by DerellLicht** [comment] 2021-01-02 23:21
Aye, I figured that out awhile later!!  I thought I deleted this post, 
but I guess I didn't.

And it works Beautifully!!  Thank you SOOOO much!!!!!!!!!!!!!!

Derell Licht

**Comment by blackwidowfarms** [comment] 2021-01-03 00:16
Yah thanks everyone here at openshell, it works awesome now, totally stoked!





----- Original Message -----

**Comment by bonzibudd** [comment] 2021-03-22 04:21
@ge0rdi 

I made an issue for that problem here: #602. A prompt should work fine, but it should avoid that broken "in-between" state if possible.
