### ISSUE TITLE
Classic toolbar wont go away in Windows 11 Explorer

### ISSUE THREAD

**Issue by k-basara** [Open-Shell/Open-Shell-Menu#1944] opened 2024-07-04 01:30 UTC
### Describe the bug

Classic toolbar still shows after I choose to not show it.    

### Area of issue

Windows Explorer

### To reproduce

1. Open File Explorer
2. Right click on classic toolbar and uncheck it, toolbar disappears
3. Close Explorer
4. Open Explorer, the toolbar still shows

### Open-Shell version

4.4.191

### Windows version

Windows 11 23H2 22631.3737

**Comment by ge0rdi** [comment] 2024-07-04 04:16
Duplicate of #1526.

**Closed by ge0rdi** 2024-07-04 04:16 UTC
Labels: Bug
