### ISSUE TITLE
Explorer file grouping broken

### ISSUE THREAD

**Issue by Hoanzn** [Open-Shell/Open-Shell-Menu#1290] opened 2023-01-15 22:14 UTC
### Describe the bug

Open-Shell 4.4.188 and previous versions break multi-select functionalities of the file explorer and window dragging on Windows 11.

Observed on 
- Windows 11 22H2 22621.1105 
- NVIDIA 3060 driver version 528.02 on a 4K monitor

### Area of issue

Windows Explorer

### To reproduce

1) On Desktop, select two or more files with rubberband or shift/ctrl holding
2) Moving on desktop fails, instead one/more file is/are deselected, and the
   first selected file is loaded into its default application (e.g., *.jpg + Irfanview)
3) Application windows and file explorer window show erratic behavior if moved
   with the mouse (left-click + hold and move). Windows loose focus, are re-opened
   to full size or only moved a small distance before being released while being 
   dragged by the mouse.
4) Uninstall Open-Shell 4.4.188 and reboot: Specified behavior is restored (good case)
5) Reinstall of Open-Shell 4.4.188: Behavior described in steps 1) ... 3) show up again
    (bad case)

### Expected behavior

After grouping files by rubberand or multi-select, it should be possible to
move/copy the selection on desktop or in between different directories
using the file explorer.

### Open-Shell version

4.4.188

### Windows version

Windows 11 22H2 22621.1105 

### Additional context

Suspected a video-card driver issue. However, removal of the 
NVIDIA driver and working on a lower resolution with the Windows
standard driver did not change the described malfunctioning.
Also a complete re-install and reboot of the newes NVIDIA driver
did not resolve the issue.

**Comment by ge0rdi** [comment] 2023-01-16 06:17
I can't reproduce anything like that :(
Are you using some other _tweaking_ software that could affect behavior of File Explorer?

**Comment by Hoanzn** [comment] 2023-01-16 08:08
Hi,there is no other SW like TweakUI installed.However, the described malfunction maytake some time (a few weeks on my PC) to show up, but when it appears, it survives booting and uninstalls/reinstalls, and it is100 % reproducable.I had similar behavior on another Pc withan old NVIDIA K2000, and on a Dell PrecisionM4800 Workstation. All these being legacy hardware which do not meet W11 requirements but nevertheless running quite well otherwise.RegardsThomasThomas HirschmannLangauenstrasse 883278 TraunsteinTel. 0861 98829931Mobil 0152 05342757EMail ***@***.*** 16.01.2023 07:17 schrieb ge0rdi ***@***.***>:
I can't reproduce anything like that :(
Are you using some other tweaking software that could affect behavior of File Explorer?

**Comment by ge0rdi** [comment] 2023-01-16 08:36
> the described malfunction maytake some time (a few weeks on my PC) to show up

I'm sorry, but without some reasonable steps to reproduce this the probability that someone would even investigate this is close to zero :(

So I guess I'd just close this.
Feel free to reply here if you will be able to reproduce it more easily.

**Closed by ge0rdi** 2023-01-16 08:36 UTC
Labels: Bug, unable to reproduce, Windows 11, Classic Explorer

**Comment by Hoanzn** [comment] 2023-01-16 10:04
That's ok for me. As soon as i find a way to reproduce this bug from scratch withoutdelay, I let you know. At least its documentednow.RegardsThomasThomas HirschmannLangauenstrasse 883278 TraunsteinTel. 0861 98829931Mobil 0152 05342757EMail ***@***.*** 16.01.2023 09:36 schrieb ge0rdi ***@***.***>:

the described malfunction maytake some time (a few weeks on my PC) to show up

I'm sorry, but without some reasonable steps to reproduce this the probability that someone would even investigate this is close to zero :(
So I guess I'd just close this.
Feel free to reply here if you will be able to reproduce it more easily.
