### ISSUE TITLE
Open-Shell doesn't index Settings

### ISSUE THREAD

**Issue by crwn1337** [Open-Shell/Open-Shell-Menu#177] opened 2019-06-07 06:50 UTC
<details>
  <summary>Windows Update</summary>
  <img src="https://user-images.githubusercontent.com/38888474/59085434-3ea09b00-8907-11e9-8d4e-e1b25b40192f.png" alt="windows">
  <img src="https://user-images.githubusercontent.com/38888474/59085255-ab676580-8906-11e9-8ffe-177f688540ba.png" alt="openshell">
</details>

<details>
  <summary>Windows Defender</summary>
  <img src="https://user-images.githubusercontent.com/38888474/59085507-832c3680-8907-11e9-806c-c9c739215f9a.png" alt="windows">
  <img src="https://user-images.githubusercontent.com/38888474/59085508-832c3680-8907-11e9-8bdb-b1a289dd6bc1.png" alt="openshell">
</details>

These are just a few examples.

<details>
  <summary>OS/Settings</summary>
  <img src="https://user-images.githubusercontent.com/38888474/59085313-d94caa00-8906-11e9-937b-7c1fef163bed.png" alt="windows">

  <a href="https://github.com/Open-Shell/Open-Shell-Menu/files/3264705/Menu.Settings.txt">Menu.Settings.txt</a>

</details>

**Comment by ibuprophen1** [comment] 2019-06-07 20:16
I'm not completely sure what your asking about/referring to with this. 

Are you referring to the Windows Indexing? 


~Ibuprophen

**Comment by mhoelzel142** [comment] 2019-06-07 23:21
I'm guessing that crwn1337 is referring to individual settings inside the Settings app - i.e. System, Accounts, Apps, Privacy, Ease of Access, etc.

**Comment by ge0rdi** [comment] 2019-06-09 14:25
@crwn1337 
For some reason `Modern Settings` are not searched on your machine. 
According to config you provided it seems they should be enabled.

Please, create advanced log using these steps:
- In registry key `HKEY_CURRENT_USER\Software\OpenShell\StartMenu\Settings`
- Create item named `LogCategories` with value `0xC0`
- Press Start button and type some query (as you did before)
- There should be `%LOCALAPPDATA%\OpenShell\StartMenuLog.txt` file created
- Attach it here

**Comment by crwn1337** [comment] 2019-06-10 08:06
[StartMenuLog.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/3271135/StartMenuLog.txt)

**Comment by ge0rdi** [comment] 2019-06-10 15:58
Seems you are missing `.settingcontent-ms` files in:
`%LOCALAPPDATA%\Packages\windows.immersivecontrolpanel_cw5n1h2txyewy\LocalState\Indexed\Settings`
Or they are not indexed.

Try solutions proposed here:
https://superuser.com/questions/950102/what-do-i-have-to-index-in-order-to-search-the-windows-control-panel-in-win10/1182041

And let us know if it helped.

**Comment by crwn1337** [comment] 2019-06-10 19:07
`%LOCALAPPDATA%\Packages\windows.immersivecontrolpanel_cw5n1h2txyewy\LocalState` does not exist.

I already tried to re-index, use the troubleshooter, creating a new account, and mess with the language and nothing has worked.

**Comment by ge0rdi** [comment] 2019-06-11 04:46
This is the same thing as #57.
I'm afraid that for now we don't have any solution for that case.

`Open-Shell` looks for _modern settings_ in `%LOCALAPPDATA%\Packages\windows.immersivecontrolpanel_cw5n1h2txyewy\LocalState`.
Also original `Classic-Shell` did it that way.

Though it seems recent Win10 versions don't have those files (I've tried to install 1809 from scratch and they were missing as well) :(

I have no clue where official start menu gets those settings.

**Comment by ge0rdi** [comment] 2019-06-11 04:46
Duplicate of #57

**Closed by ge0rdi** 2019-06-11 04:46 UTC

**Comment by crwn1337** [comment] 2019-06-12 20:30
I know this is closed, but this might help.
I found that `C:\Windows\ImmersiveControlPanel\SystemSettings.dll` contains all the ms-settings

**Comment by ge0rdi** [comment] 2019-06-13 04:50
@crwn1337 
That's very good catch 👍 

You should write it to original issue #57 and we can continue discussion there.
