### ISSUE TITLE
Windows 10 1903 

### ISSUE THREAD

**Issue by ghost** [Open-Shell/Open-Shell-Menu#182] opened 2019-06-24 19:10 UTC
I have two PCs with have Open Shell 4.4.138, and upgraded to Windows 1903, no issues at all.  I have just helped out someone else (1903) and with the In built menu, if you click on the start button it stays on the screen, but with Open Shell it might come up and then disappear, after a split second, or not appear at all.

I have tried uninstalling, reinstall, also the Reset to Defaults option and nothing works ?

Thank you

**Comment by blackcrack** [comment] 2019-06-25 02:15
@ge0rdi had build the nightly build, maybe is this interesting for ge0rdi .

**Comment by ibuprophen1** [comment] 2019-06-25 02:28
It looks like this issue may be a duplicate of the https://github.com/Open-Shell/Open-Shell-Menu/issues/167 issue... 

Can you please check that issue out to see if I'm correct @jamesblueuk? 


~Ibuprophen

**Comment by ge0rdi** [comment] 2019-06-25 04:47
@jamesblueuk 
You may try latest [stable release](https://github.com/Open-Shell/Open-Shell-Menu/releases) to see if it will work for you.

If it won't work, then please try to [enable logging](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log) and provide `Open-Shell` log. 
Hopefully that will give us some hint about what's going on.

**Comment by jamesblueuk** [comment] 2019-06-25 09:56
> @jamesblueuk
> You may try latest [stable release](https://github.com/Open-Shell/Open-Shell-Menu/releases) to see if it will work for you.
> 
> If it won't work, then please try to [enable logging](https://github.com/Open-Shell/Open-Shell-Menu/wiki/How-to-obtain-advanced-Open-Shell-Menu-log) and provide `Open-Shell` log.
> Hopefully that will give us some hint about what's going on.

When i am next helping him, i will test out 4.4.131.   I made the mistake of going to https://www.majorgeeks.com/files/details/classic_start.html, they do not mention it is a beta, but they have 4.4.138, which works on both mine 1903


Thank you

**Comment by jamesblueuk** [comment] 2019-06-25 09:58
> It looks like this issue may be a duplicate of the #167 issue...
> 
> Can you please check that issue out to see if I'm correct @jamesblueuk?
> 
> ~Ibuprophen

I check out 167, it does not look like the same issues, as they are not mentioning about if you click on start if comes up okay, but then goes off.  It works for me on 1903 x 2 PCs.   I did not realise 138 was not the latest version, as it was at https://www.majorgeeks.com/files/details/classic_start.html, next time i am helping him out, i will try the latest stable version from this website, which is currently 131.

**Closed** 2020-08-31 20:05 UTC
