### ISSUE TITLE
Taskbar transparency no longer works after Windows 11 update KB5023706 from 03/15/2023

### ISSUE THREAD

**Issue by OliverKosmo** [Open-Shell/Open-Shell-Menu#1358] opened 2023-03-17 16:43 UTC
### Describe the bug

I'm using Windows 11 (22H2 (Build 22621.1413)) with the very latest updates with AMD CPU 3900x, 32GB RAM, NVidia GPU 3060Ti with latest Studio driver V528.49. I installed the Open-Shell Menu V4.4.188. Under the "Taskbar" tab, the "Customize taskbar/taskbar look/Transparent" setting no longer works, the taskbar opacity is set to 0 for full transparency. Tried a few things, nothing helped. The taskbar now has the so-called accent color of Windows. For me in a rich shade of blue as a full color.
Everything had been working fine so far, the trouble came immediately after the Windows update KB5023706 from March 15, 2023 (2023-03 Cumulative Update for Windows 11 Version 22H2 for x64-based systems).

### Area of issue

Taskbar

### To reproduce

I installed the Open-Shell Menu V4.4.188. Under the "Taskbar" tab, the "Customize taskbar/taskbar look/Transparent" setting no longer works, the taskbar opacity is set to 0 for full transparency. Tried a few things, nothing helped. The taskbar now has the so-called accent color of Windows. For me in a rich shade of blue as a full color.
Everything had been working fine so far, the trouble came immediately after the Windows update KB5023706 from March 15, 2023 (2023-03 Cumulative Update for Windows 11 Version 22H2 for x64-based systems).

### Expected behavior

Everything had been working fine so far, the trouble came immediately after the Windows update KB5023706 from March 15, 2023 (2023-03 Cumulative Update for Windows 11 Version 22H2 for x64-based systems).

### Open-Shell version

4.4.188

### Windows version

Windows 11 22H2 (Build 22621.1413)

**Comment by puzzler42** [comment] 2023-03-18 03:14
I am having a similar issue since the same update.  I think however that the Windows taskbar may be blending or in front of the Open-Shell one since changing the color of the Open-Shell taskbar between #000000 and #FFFFFF changes the color somewhat (not a lot, really just the shade).  I have the built-in Windows taskbar set to transparent if that matters.  I have tried changing Windows's accent color to the desired taskbar color but while this works everywhere else it should appear, the taskbar is slightly darker than it should be even with a White, opaque Open-Shell taskbar.

**Comment by OliverKosmo** [comment] 2023-03-18 05:30
> I am having a similar issue since the same update. I think however that the Windows taskbar may be blending or in front of the Open-Shell one since changing the color of the Open-Shell taskbar between #000000 and #FFFFFF changes the color somewhat (not a lot, really just the shade). I have the built-in Windows taskbar set to transparent if that matters. I have tried changing Windows's accent color to the desired taskbar color but while this works everywhere else it should appear, the taskbar is slightly darker than it should be even with a White, opaque Open-Shell taskbar.

Thanks for your cooperation ...

**Comment by daknut** [comment] 2023-03-18 09:10
The Moment 2 Build notes on Microsoft's Site notes that a couple of programs that alter the UI (User Interface) are not functioning properly (https://support.microsoft.com/en-us/topic/march-14-2023-kb5023706-os-build-22621-1413-9d3f2de5-08e7-4462-8fba-d944201f4ae1) and they suggest uninstalling the programs before installation. As Open Shell alters the UI, I'm guessing that the problem is related to this.

I had a few laptops that I needed to update. My first caused the problem. I uninstalled Open Shell and re-installed and nothing changed. I uninstalled Open Shell, uninstalled the update, re-installed it. No change. I re-installed Open Shell and still no change.

The third laptop, I uninstalled Open Shell BEFORE installing the update and got the same problem. I am fairly sure that the problem lies with an Open Shell conflict but can't work out a way to fix it.

I want to mention that I think that there's also an issue with the Widgets following the Update as the weather doesn't always load on the Taskbar - and neither do the widgets always, either.

**Comment by OliverKosmo** [comment] 2023-03-18 15:28
Thanks for your cooperation ..., daknut

**Comment by Teletele-Lin** [comment] 2023-03-19 01:23
I have the same problem, I have been using openshell to achieve a transparent taskbar effect, but after updating the KB5023706 patch, the software does not work properly, setting transparency can only achieve the effect of a slight change in the taskbar color, but not full transparency.

**Comment by OliverKosmo** [comment] 2023-03-19 07:01
Thanks for your cooperation ..., Teletele-Lin

**Comment by daknut** [comment] 2023-03-19 07:35
Post https://github.com/Open-Shell/Open-Shell-Menu/issues/1342 relates to the same issue, the effect of the optional update that achieved the same changes on the Taskbar as the Cumulative update. Those affected here still need to confirm the problem with the Search Button.

**Comment by Aokromes** [comment] 2023-03-19 13:20
@ge0rdi duplicate of https://github.com/Open-Shell/Open-Shell-Menu/issues/1342

**Comment by daknut** [comment] 2023-03-19 14:27
> @ge0rdi duplicate of #1342

Duplicate of previous post :)

**Comment by ge0rdi** [comment] 2023-03-19 17:55
Yup. This is known issue.
MS is gradually changing taskbar to use new XAML framework and it works in completely different way.
So customizations simply don't work. And they won't work until we'll find some way to _hook_ into that framework.

**Closed by ge0rdi** 2023-03-19 17:55 UTC
Labels: Bug

**Comment by Teletele-Lin** [comment] 2023-04-02 00:30
https://mcnba.lanzouy.com/ibsAR0raz78d 
run .\ViVeTool.exe /disable /id:26008830 /variant:2 
This tool can restore the taskbar.

**Comment by Rich1Up** [comment] 2023-05-12 18:14
yeah, can confirm - the updates did this.  What a bummer.  On the plus side, I now have a bunch of new apps and plugins for Windows that I didn't ask for or want

**Comment by LeeBinder** [comment] 2024-04-12 20:11
> https://mcnba.lanzouy.com/ibsAR0raz78d run .\ViVeTool.exe /disable /id:26008830 /variant:2 This tool can restore the taskbar.

https://github.com/thebookisclosed/ViVe/releases
