### ISSUE TITLE
Regression: Shutdown button have no effect when two sessions opened

### ISSUE THREAD

**Issue by SuperPat45** [Open-Shell/Open-Shell-Menu#1303] opened 2023-01-22 11:42 UTC
### Describe the bug

After updating to the last open-shell version, the shutdown button as no effect when there is another session opened.

### Area of issue

Start menu

### To reproduce

1. Open start menu to change user
2. Open another session with a second account
3. Open start menu and click shutdown button
4. Nothing append...

### Expected behavior

It must show the confirmation dialog saying that there is another session opened.

### Open-Shell version

4.4.189

### Windows version

Windows 10 22H2

### Additional context

Edit: Tested with version 4.4.170 and not problem.

**Comment by bonzibudd** [comment] 2023-01-24 04:29
Just saw this issue. I can confirm this on Win10 and Win11.

**Comment by uom42** [comment] 2023-01-28 17:53
The same situation on the MS Terminal server.
After connecting the second and any next session, even if these sessions are completed.

**Comment by ge0rdi** [comment] 2023-01-28 18:18
> But the UAC dialog is displayed

This is weird.
Can you post screenshot of it (with details expanded, so we can see what triggered the dialog)?

**Comment by uom42** [comment] 2023-01-30 15:37
When only first user logged in after Windows started, we see UAC-window (when click reboot/shutdown), and all work well.

But when second user logged in, even in first user session, after UAC-window (when click reboot/shutdown) nothing happens.

Reboot or Shutdown don't work.
Sleep, Logoff - works well.


Reboot UAC:

![Reboot](https://user-images.githubusercontent.com/6280840/215521881-ffe3121b-d0e7-4b58-8672-ac27706b4a23.png)


Shutdown UAC:

![Shutdown](https://user-images.githubusercontent.com/6280840/215521914-07ce4e8e-d441-44a8-bb46-5b439143349d.png)

**Comment by ge0rdi** [comment] 2023-01-30 16:23
Interesting. You are not supposed to see any UAC dialog.
Do you get such UAC dialog also when you do shutdown/reboot from standard Windows start menu?

Could open console (under you normal user) and provide output of `whoami /all` command?

**Comment by uom42** [comment] 2023-01-30 18:27
> Do you get such UAC dialog also when you do shutdown/reboot from standard Windows start menu?

Yes, I get UAC anyway. Perhaps this may be a feature of Win Server? idk.

But there are some differences in  API params:

Reboot:

![Reboot Compare](https://user-images.githubusercontent.com/6280840/215557234-8f485b43-ad3b-4c6d-9e1f-f95862eb693c.png)

Shutdown:

![Shutdown Compare](https://user-images.githubusercontent.com/6280840/215557295-36238cd9-bd0b-4570-8f28-4cad6c851bce.png)


------------------
I make an some experiments...
And so on, the first user - have Admin rights. The second user don't have admin rights.

1) UAC from OpenShell start menu don't works (in first user session) after second user logon!
2) UAC from standart WinServer start menu still works (in first user session) after second user logon!
3) But in second user session (without admin rights), with OpenShell, we don't have even UAC window! Just nothing happens when clicks on OpenShell Shutdown/Reboot (Logoff/Sleep works).
The Second user session (without admin rights), have not items in Standart WinServer start menu to reboot/shutdown (have only logoff). So I could not check if these items work under restricted user rights.

**Comment by ge0rdi** [comment] 2023-01-30 18:33
Could you post output of `whoami /all` for both users?

**Comment by uom42** [comment] 2023-01-30 18:44
> Could you post output of `whoami /all` for both users?

Second user (without admin rights):

![whoami](https://user-images.githubusercontent.com/6280840/215566876-ef54753c-556f-4625-8844-fce2c02d5a67.png)

**Comment by ge0rdi** [comment] 2023-01-30 18:52
> Second user (without admin rights):

This looks good. And it is expected that such user shouldn't be able to shutdown machine as he doesn't have `SeShutdownPrivilege`.

Can you provide the output of `whoami /all` also for the admin user (done from normal non-elevated console)?

Normally non-elevated admin shouldn't get UAC prompt when `SystemSettingsAdminFlows.exe` is started (it should be elevated silently). So it is weird that it doesn't work that way.
But since also original Start menu works that way, there is probably something configured differently on servers.

Anyways, the only issue here is that one is unable to shutdown/reboot when more users are logged in.
And this will be addressed for sure.

**Comment by uom42** [comment] 2023-01-30 18:55
> Could you post output of `whoami /all` for both users?

First user - with admin rights:

![whoami administrator](https://user-images.githubusercontent.com/6280840/215568912-25cfaba9-3244-4dd8-bd10-3a36b027c60b.png)

**Comment by uom42** [comment] 2023-01-30 18:58
> This looks good. And it is expected that such user shouldn't be able to shutdown machine as he doesn't have `SeShutdownPrivilege`.

May be we need to check this out in OpenShellMenu... and show some message or some also...



> But since also original Start menu works that way, there is probably something configured differently on servers.

Server settings is default, after install. This is test server instanse, just deployed.

**Comment by uom42** [comment] 2023-01-30 19:01
> ...that one is unable to shutdown/reboot when more users are logged in. And this will be addressed for sure.

May be this API codes may help us?:

![Reboot Compare](https://user-images.githubusercontent.com/6280840/215570184-4fbafe91-82e7-4351-922f-aeed48b270b0.png)


![Shutdown Compare](https://user-images.githubusercontent.com/6280840/215570201-e465bb69-3be3-4558-aed1-429112c3b394.png)

**Comment by ge0rdi** [comment] 2023-01-30 19:05
> May be we need to check this out in OpenShellMenu... and show some message or some also...

Well, ideally the shutdown and reboot buttons should be not present if the user doesn't have rights for that.
I think Windows start menu does it that way.

We can improve this in the future eventually.

> Server settings is default, after install.

I meant that something is probably configure differently in server OSes comparing to non-server ones.
Like silent elevation disabled or so.
Hard to tell, but it doesn't matter much.

> May be this API codes may help us?

Nope.
I know where is the problem with multiple users. Need to just implement confirmation dialog.
This will be fixed for sure.

**Comment by uom42** [comment] 2023-01-30 19:16
> I know where is the problem with multiple users. Need to just implement confirmation dialog.

I think I can guess what do you mean.
Please note that the problem with shutting down/rebooting from the first user appears NOT ONLY when the second user session is still running, but also AFTER the second session is long over!

**Comment by SuperPat45** [comment] 2023-02-18 18:43
I reinstalled the version 4.4.170, and it does not have the bug. 
So this bug is definitively a regression.

**Comment by ge0rdi** [comment] 2023-07-19 18:56
@SuperPat45 
I'm sorry for delay, but I guess I have fixed it.
Please, try with build from #1601 PR if you can.

**Comment by SuperPat45** [comment] 2023-07-21 16:13
Sorry, I can't help:
Since I have reinstalled Windows 10, I no longer have this bug with OpenShell version 4.4.170,
the confirmation dialog saying that there is another session now appear.

**Comment by kswartz26** [comment] 2023-07-21 17:40
I tried it, and can confirm this resolves the issue. OpenShell now correctly prompts whether to continue because there are other users logged in, and goes forward with the action when answering Yes. Thanks for the fix!

**Comment by ge0rdi** [comment] 2023-07-22 05:55
@kswartz26 
Thank you for confirmation.

**Comment by ge0rdi** [comment] 2023-07-24 16:33
Fixed in 4.4.190 .

**Closed by ge0rdi** 2023-07-24 16:33 UTC
Labels: Bug
