### ISSUE TITLE
Win 10 x64 Start button on 2nd monitor shows Windows Start Menu

### ISSUE THREAD

**Issue by MightyDrakeC** [Open-Shell/Open-Shell-Menu#237] opened 2019-10-09 05:21 UTC
Just upgraded from Classic Shell to Open Shell.  I'm running Actual Multiple Monitors to get individual taskbars on my two monitors.  In the past, the Classic Shell menu showed when clicking on the Start Button on either monitor.  Now, clicking on the Start Button on the second monitor shows the Windows Start Menu

**To Reproduce**
1. Running Actual Multiple Monitors v8.14.1 and Open Shell v4.4.131
2. On second screen, click Start Button
3. Stock Windows Start Menu displays

**Expected behavior**
Should see the Open Shell menu when clicking either Start Button

**Screenshots**

**Version:**
 - Open-Shell: 4.4.131
 - OS: Windows 10 x64 18362.356

**Additional context**

**Comment by XenHat** [comment] 2019-11-16 16:45
I cannot reproduce this issue on `Microsoft Windows [Version 10.0.18362.476]`.
Clicking the Start Menu icon or pressing the [WIN] key while focused on any of my three (3) monitors behaves correctly.

**Comment by Ibuprophen** [comment] 2019-11-16 19:46
I forgot to mention that I couldn't reproduce this either using Windows 10 Pre & Windows 8.1 Pro. 

~Ibuprophen

**Comment by MightyDrakeC** [comment] 2019-11-16 20:15
It's still happening, here.

Which multi-taskbar programs are you using?

Is there a setting I missed somewhere?

**Comment by amelora** [comment] 2020-07-26 17:23
According to Actual Tools, this bug is already fixed and the fix will be available in their next release.

See:
https://www.actualtools.com/ru/forum/read.php?FID=10&TID=5313

**Comment by MightyDrakeC** [comment] 2020-07-26 18:55
Appreciate you taking the time to tell me.  On the machine where I was seeing the issue, I've upgraded to a wide monitor.  So, unfortunately, I can't test it.

**Comment by Ibuprophen** [comment] 2020-07-26 20:27
@MightyDrakeC, if this issue is resolved or no longer an issue, maybe you should close it. 

I just try to encourage the OP Issuer's to close issues that are no longer an issue in one form or another. I only close those that really requires that type of intervention (so to speak). 

Thanks a bunch for your time and understanding! :-) 


~Ibuprophen

**Comment by MightyDrakeC** [comment] 2020-07-26 21:12
Ah, sure, I can do that.  I'm still a relative newbie to Github conventions.

**Closed** 2020-07-26 21:12 UTC
