### ISSUE TITLE
WHERE START BUTTON [Bug report]

### ISSUE THREAD

**Issue by MCAlexisYT** [Open-Shell/Open-Shell-Menu#1085] opened 2022-08-06 17:02 UTC
**Describe the bug**
The issue is that the the task bar decided to turn into that of Windows 8 in terms of functionality but without the start screen. I couldn't open the start menu with a mouse if I had it set to anything but the classic start button option.

**To Reproduce**
1. Install Windows 7 in Virtual Box
2. Install Open Shell (might require a browser other than IE)
3. Open the config applet
4. Click on "Replace start button" and then "Aero" if it isn't checked
5. **WHERE START BUTTON**

**Expected behavior**
The start button should show up.

**Screenshots**
![WHERE START BUTTON](https://user-images.githubusercontent.com/78766083/183258656-e1b930e6-e35a-4ab9-82a0-6216fa32d3ce.PNG)

**Version:**
 - Open-Shell: [e.g. 4.4.170]
 - OS: [e.g. Windows 7 SP1 7601]

**Additional context**
I was trying to customize my Windows 7 VM specifically created for making Minecraft mods with "MCreator" because it suddenly decided to break itself on the host machine.

**Comment by blackcrack** [comment] 2022-08-06 17:19
is a known issue, your win7 it's not update to the actual updates..  
so the native installed and then tried..  
this works if you have install the updates ...  
and try to take the classic button, this should work..  
or an other, Custom... (but i did have not try) i have every directly updated.

**Comment by MCAlexisYT** [comment] 2022-08-06 17:33
@blackcrack 1: Are you speaking english or engrish? 2: Whatever you suggested didn't work.

**Comment by blackcrack** [comment] 2022-08-06 17:58
@MCAlexisYT, 1. it seems your nose is not normal.. your an alien ? 
2. you can close this issue, because i bet, there is no programmer who fix it, because to less Programmers here in the Project..

**Comment by Ibuprophen** [comment] 2022-08-06 21:09
@MCAlexisYT, Do you have the last/latest version of Windows 7?

I believe the last version is "Service Pack 1 (6.1.7601.24499)" that was released on 9 Feb 2011. 

~Ibuprophen

**Comment by CTVCAM8** [comment] 2022-08-07 03:14
If @blackcrack is saying that it could be related to a lack of updates in your VirtualBox Win7, 
I found this web page to get as many Win7 updates as possible to 2016,
and it turns Windows 7 update service back on for newer (mostly Defender) updates after that date: 

https://www.howtogeek.com/255435/how-to-update-windows-7-all-at-once-with-microsofts-convenience-rollup/


update first Windows6.1-KB3020369 (Small file)
restart

update second windows6.1-kb3125574 (Large file)

If it makes no difference, you could repair\uninstall Open-Shell 4.4.170 or install the old Classic Shell 4.3.1 to see any difference.

**Comment by CTVCAM8** [comment] 2022-08-07 17:28
@MCAlexisYT 
Today, I had to confirm myself.

Host Win10
I installed Windows 7 64bit on VirtualBox version6.1.36r152435
Winver says 6.1(Build 7601: Service Pack 1)
Did not install any later updates.

Installed only the start menu of Open-Shell 4.4.170
Results: same as you-FAIL.


Uninstalled Open-Shell 4.4.170, restarted
Installed Classic Shell 4.3.1
Results: Works correctly. The start button icon is visible and works no matter which button option is selected.
Start menu icons (inside the menu) are visible.

------------------------------------------------------ 

Next test for additional Windows 7 updates.
Installed both updates.
Did not connect to the internet.
Installed Open-Shell 4.4.170
Results: Still FAILS.

Also tried OpenShell 4.4.160
Results: Still FAILS.


Uninstalled Open-Shell, and restarted.
Installed Classic Shell 4.3.1
Results: Works correctly.

---------------------------------------------
Test Windows 7 64-bit installed on a physical SSD (not virtual) and fully updated. 
Results: Classic Shell 4.3.1 and Open-Shell 4.4.170 work correctly.

----------------------------------------------

This is the first time I have ever used VirtualBox with Windows 7.
I have no idea why Open-Shell fails in VirtualBox 
unless there are one or more Windows updates that change the results.

**Comment by Ibuprophen** [comment] 2022-08-07 22:47
The VirtualBox (aka VM) has a few items regarding permissions and directories that would be challenging for me to get into via text. 

The following link is a conversion that may have some very helpful clarity and insight specific to this topic... 

http://www.classicshell.net/forum/viewtopic.php?f=7&t=7482

Good Luck! 

~Ibuprophen

**Comment by CTVCAM8** [comment] 2022-08-08 01:11
HI @Ibuprophen

Wow, that's big-time issues msemp had. I didn't have to deal with permissions and directories. VirtualBox set itself up by itself.
I don't find VMs any good for me. They are slow and crippled. Great for people with laptops though.
My main computer has bays at the front, so I can just slide in a different SSD OS from XP to Win 11.

Getting back @MCAlexisYT situation.
About all those Windows 7 updates that had to get installed to get Open-Shell 4.4.170 working, 
whereas Classic Shell 4.3.1 always worked with or without any Windows updates after SP1
I'm taking a wild guess that .NET Framework 4.8 must have something to do with it.

**Comment by blackcrack** [comment] 2022-08-08 05:18
Hi @Ibuprophen  and @CTVCAM8 ,

This issue is also if i install a Hardware, not only if i install it in Virtualbox.
But i have my own updatescript with the whole updates from the last Years
hmm.. if any want could he download the whole updates from the MSUpdate Kataloge and make his own
updatepackage for Win7 (ab bit huge pagage, but useful for Win7)..

[setup-update-batch-1.69.bat 2022-08-08 07-01-20.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/9278822/setup-update-batch-1.69.bat.2022-08-08.07-01-20.zip)

this package do i every run over night, if i have a fresh installed Win7, first the reg-strings then Autologin for automatical login,  
then from 2020-12 BypassESU-v11  for all updates later as  behind the "onceautostart" via registry the own file
automatical running via " :MSI " step who runs directly at the last Checkpoint " :MSI " at the script

with the list have you a download list so far all updates who was need in the last years for a proper running Win7,
include ie-install and later "Edge" install ..

ah ja important, the batch-file must be encoded in OEM850 , otherwise becomes bugs, at best, you take the notepad2 and follow the instructions from the header who i have wrote..

https://github.com/zufuliu/notepad2/releases
[Notepad2_i18n_Win32_v4.22.07r4278.zip  1.26 MB 22 days ago](https://github.com/zufuliu/notepad2/releases/download/v4.22.07r4278/Notepad2_i18n_Win32_v4.22.07r4278.zip)
[Notepad2_i18n_x64_v4.22.07r4278.zip  1.41 MB 22 days ago](https://github.com/zufuliu/notepad2/releases/download/v4.22.07r4278/Notepad2_i18n_x64_v4.22.07r4278.zip)


best regards and
have fun
Blacky

**Comment by CTVCAM8** [comment] 2022-08-08 06:09
@blackcrack. 
That's generous of you to provide all your info. Looks like you've done a lot of work.
For all I know someone may have already slipstreamed all the new Windows & driver updates into a Windows 7 iso 
as they have done with Windows 98,& XP which makes it so much easier. 
I don't have time to scour the internet for it.

Well, it's up to @MCAlexisYT to decide what to do.

What is clear is the issue is not a bug. 
New versions of Open-Shell just need all Windows 7 updates to work correctly.

**Closed** 2022-08-24 08:40 UTC
