### ISSUE TITLE
Open-Shell toolbar no longer compatible with Windows 11 22H2

### ISSUE THREAD

**Issue by Truchin** [Open-Shell/Open-Shell-Menu#1207] opened 2022-11-14 15:31 UTC
Open-Shell 4.4.180

Since installing tabs in Windows 11 22H2 explorer the toolbar has issues.
It remains immobilized on the left.
Is there a solution?
Thank

**Comment by ge0rdi** [comment] 2022-11-14 15:55
Duplicate of #1180.
Please, don't create duplicate issues.

**Closed by ge0rdi** 2022-11-14 15:55 UTC

**Comment by Truchin** [comment] 2022-11-14 16:12
But there must be a solution!? I must not be the only one in this case.
