### ISSUE TITLE
Doesn't respect system-wide theme preference

### ISSUE THREAD

**Issue by JamesYeoman** [Open-Shell/Open-Shell-Menu#386] opened 2020-06-22 22:57 UTC
I have Dark Theme enabled on Windows 10, and the Classic Shell theme is jarring and it's clearly an addon to the shell as a result, rather than fitting in seamlessly

Here's a screenshot
![image](https://user-images.githubusercontent.com/21042602/85343162-0f45d780-b4e4-11ea-8e5e-90faedebfe1f.png)

**Comment by glowingwire** [comment] 2020-06-23 00:04
I believe that is controllable in settings

**Comment by NebelNidas** [comment] 2020-06-29 17:41
Duplicate of #361.

**Closed** 2020-08-30 19:59 UTC
Labels: Refer/Duplicate/Similar of/to Another Issue...
