### ISSUE TITLE
Pinned to Classic Start Windows 10 app will cause the app to not have a taskbar image on launch

### ISSUE THREAD

**Issue by madmrmax** [Open-Shell/Open-Shell-Menu#97] opened 2018-10-17 19:13 UTC
I noticed this on Windows 10 1803 and 1809 build -- if you pin a Windows 10/modern app like Edge to the Classic Start menu/Open Shell menu, then launch the app, then close the app, then launch the app again (sometimes you don't need to launch twice) the app will not have a taskbar icon.

Repro steps (assuming you have Classic Start installed, assuming you have the "Show Apps Menu" option enabled)
1. Click Start, then click the Apps menu to see a list of Windows 10 apps like Paint 3D
2. Right click on Paint 3D and choose "Pin to Start Menu (Classic shell)"
3. Close start menu
4. Open start menu and click on Paint 3D that was pinned
5. Verify that the app Paint 3D has an app icon in the taskbar
6. If needed, close Paint 3D and then perform steps 4 and 5 again.

Expected results: Modern apps have a icon in the task bar

The issue I believe is that Classic Start is specifying the icon used for the process on launch. This is great for Win32 apps but it appears as though this is causing problems for modern apps. I didn't see this issue in 1703/1709.

**Comment by madmrmax** [comment] 2018-10-24 17:04
I noticed that as well sometimes as I was doing different repros. Usually restarting the app like Paint3D after I unpin the app restores the icon. Note that you must _make sure and unpin the app from classic start_ before exiting. Somehow the process of pinning to classic start is what is causing the issue!!

I tried a few more things and somehow it looks like executing the app from the "recent apps" section or under the "Apps" menu _without having the app pinned to classic start_ will always work and show the app icon on the task bar. As soon as you pin to classic start executing the app from those previous locations now will not show the icon on the task bar.

1. Click Start, then click the Apps menu to see a list of Windows 10 apps like Paint 3D
2. Launch Paint 3D and verify the app icon is on the task bar ** (it does have the icon) **
3. Close Paint 3D
4. Goto the Apps Menu and right click on Paint 3D and choose "Pin to Start Menu (Classic shell)"
5. Close classic start menu
6. Open classic start menu and _in the apps menu_ click on Paint 3D to start it
7. Check if Paint 3D has an app icon in the taskbar ** (does not have icon in the task bar) **
8. If needed, close Paint 3D and then perform steps 6 and 7 again.
9. Close Paint 3D
10. Open classic start and find the pinned Paint 3D that was pinned in step 4. Right click on Paint 3D and choose "Unpin from Start Menu (Classic shell)"
11. Close classic start menu
12. Open classic start menu and _in the apps menu_ click start Paint 3D and verify the app icon is on the task bar ** (it does have the icon. If needed restart Paint 3D ) **

**Comment by CTVCAM8** [comment] 2018-10-24 19:15
By the way, I'm just a user, not a coder.
I can not duplicate what you have with instructions, even clearing cash info, uninstalling
Classic Shell 4.3.1 or Open Shell 4.4.131. Restarting system no change.
Notice in Windows 10 default menu picture, shows odd app links. 

![icon missing no shell menu installed](https://user-images.githubusercontent.com/44127216/47455223-23bd5400-d786-11e8-9dde-02e716b4d12f.png)

In my system Paint 3D does not show on the taskbar at all. Other app icons do.

![open shell pinned icontransparent](https://user-images.githubusercontent.com/44127216/47455255-43547c80-d786-11e8-8e88-d225f3657ba0.png)

You may be correct in your bug believe about the shell menu, whichever version is being used.
For me, I'm still waiting patiently for Windows 10 1809 to be debugged first.

**Comment by ibuprophen1** [comment] 2018-10-24 19:34
It looks like something minor may have happened, like a little hiccup (so to speak), where you should be able to resolve this by rebuilding the Icon Cache. 

I've successfully done this before on Windows 10 using the Second Option within the instructions, on the following link (Manual Rebuild). 

https://www.sevenforums.com/tutorials/49819-icon-cache-rebuild.html

I only mentioned the second option because I just simply didn't use the First Option so I can't personally endorse it. 

I can't guarantee that this is the "Magic Solution" but, it's very uncommon for this to be caused by other issues. 

This is only a suggestion/recommendation and I do wish you the best of luck! :-) 


~Ibuprophen

**Comment by madmrmax** [comment] 2018-10-24 19:41
CTVCAM8 - Can you try my repro steps with a Win10 app that currently does show its icon in the task bar? Something like Edge or Calculator?

**Comment by CTVCAM8** [comment] 2018-10-24 20:59
I already have edge, calculator, weather icons on taskbar already.
Will start out fresh with Health & Fitness instead. 
I'm using Open Shell.
Followed your second set of instructions.
H&F icon shows up on the taskbar.
Also tried pinned to taskbar. The icon is visible, not transparent like the Paint 3D.
Funny, Microsoft chopped this H&F app, but still shows up. Guess they will leave as a link for a while. 

To further check
Removed any pinned Weather app from taskbar, Open shell, Win 10 default menu.
Followed your steps again. Weather app icon visible on taskbar no matter which of the 5 routes taken. 
It did not show up in recent programs 1st column yet.

My Win 10 is an upgrade, not a fresh install. 

You need more people to verify your issue.

**Comment by madmrmax** [comment] 2018-10-24 21:12
Thanks for trying it out CTVCAM8! I'd love to get more people to try it out. I've tried on three laptops so far with same affect. I've tried on both 1803 and 1809. I'll keep investigating!

**Comment by CTVCAM8** [comment] 2018-10-24 21:28
Thanks, ibuprophen1 for reminding me about that Windows icon cache as it has sometimes fixed icon problems before.
Sadly with using Brink's method, along with Disk cleanup of system files, clearing Open Shell cache, playing with the other icon cache settings in open Shell. None fix this issue of mine. I never use Paint 3D or Print 3D. I'm sure this is a Windows issue as it is not the first time.

@madmrmax
Wow, that is a lot of the same issue already and very strange.

I will re-read your instructions one more time, and try a different app.
If you don't hear back from me, it means icon image shows correctly on my system.

**Comment by madmrmax** [comment] 2018-10-24 23:11
Ok. I think this issue can be closed as external. I found repro steps that cause this issue without classic-start/open-start being ever installed:

1) open start
2) drag a win10 app icon (e.g. calculator) to the desktop (use an app that is not pinned to your task bar)
3) Open Explorer and navigate to C:\programdata\microsoft\windows (replace C drive with your system drive letter)
4) Drag the Win10 app icon from step #2 to the explorer location above. Admin credentials will be required normally  
5) Launch the Win10 app by launching from the app icon from step 4.
6) Verify app icon is show in the task bar. Close and Relaunch app if needed.
7) Try launching the Win10 app from the Windows default start menu and verify again.
8) Close app
9) __NOW__ take the shortcut that is in explorer window from step 4 and drag and drop it into the "Start Menu" folder that is shown C:\programdata\microsoft\windows\start menu
10) Attempt to start the app using the shortcut from its new location. Verify that the icon is shown in the taskbar. Close and restart if needed. The app icon in task bar will never show. Try launching the app from the windows default start menu -- the app icon will not show.

Looks like windows is doing some bad magic when the app shortcut is put into the Start Menu folder. Note it can either be the \programdata\ Start Menu folder or a user folder as well-- same issue.

**Comment by madmrmax** [comment] 2018-10-24 23:12
I'll close in 24 hours to let folks see the status.

**Comment by CTVCAM8** [comment] 2018-10-24 23:46
Had to come back. Good to know you are keeping up for 24 hours.

I had to do the test again with Open Shell taskbar option turned on. 
No difference though. This time I used the Calculator app. Keeps showing correctly. 

Now my seemingly unrelated problem with invisible icons. 
I opened the so-called secret apps folder with run (shell:AppsFolder).
Double clicked on the Paint 3D and Print 3D icon in that shell folder. 
The taskbar can now show those two icons. I did your test on those and they don't disappear.
I can't say what is to blame. Somewhere something is not refreshing correctly.

**Comment by madmrmax** [comment] 2018-10-25 00:02
Based upon some things I noticed can you try the following?

1) open windows Start
2) Find any app icons that are the generic like what you highlight
![image](https://user-images.githubusercontent.com/44242726/47468026-f5ec0580-d7ad-11e8-809d-f61fd2759633.png)
3) Right click on one of those app icons and then in the context menu, select "More" followed by "Open file location". Let me know if _you do not see the Open file location_ command
4) Does the explorer window? If so, are any of those locations under any "Start Menu" folder?
5) Right click on the app icon that is selected when you performed step 3 and choose "Delete"
6) Now try and launch the app from Start menu using the "good" app icon (the one that isn't generic)

Does it work?

**Comment by CTVCAM8** [comment] 2018-10-25 00:37
Ok, now I tried your new instructions with Windows.
I did not uninstall Open Shell, just exited.


Using Weather app I can confirm your latest instructions cause the icon to NOT SHOW on the taskbar. 
The app still opens.


![app icon now missingwith last test](https://user-images.githubusercontent.com/44127216/47468848-8b899400-d7b2-11e8-9862-d696c910d9d7.png)


Once I delete the shortcut ‌in C:\programdata\microsoft\windows\start menu
I can then fix it by doing the Run shell:AppsFolder and double clicking that weather icon. It shows again.

Oddly now if I look at default Win 10 start menu, the Print 3D icon and text entry are now missing.


![print3d entry mia](https://user-images.githubusercontent.com/44127216/47469007-73664480-d7b3-11e8-93e2-93e6c54207cd.png)


 I'll get back in about 30 minutes....

**Comment by CTVCAM8** [comment] 2018-10-25 01:18
On Win 10 menu I don't see any with the white file icon,
so I can't complete your last request.
From memory, Paint 3D and Print 3D were showing up in the regular Programs list of Open Shell, as well as in the apps folder. I never moved them there. Now they are gone.



Something really screwy.
Now on Open shell, if I pin Paint 3d and Print 3D to open shell, the icons don't show correctly pinned. They do however show correct icons on the taskbar when opened the various ways.


![not correct icon](https://user-images.githubusercontent.com/44127216/47470070-048bea00-d7b9-11e8-9b31-3299a9042859.png)


I think I'm done for the day with this. I think Open Shell is having a hard time keeping up with what Microsoft is altering. :) They are always updating apps.

Goodnight.

**Comment by DragoCubed** [comment] 2018-11-21 10:35
Just so we're clear, you guys are talking about **UWP**  apps, right?

**Comment by CTVCAM8** [comment] 2018-11-21 18:06
For the test procedure of madmrmax , (the one without Classic/Open-shell being used) 
to force a shortcut into the start menu folder,  I tried Metro/ UWP apps .

Normally, I never put shortcuts like that, only just for this test.
Ok, I just tried a normal program "Winaero Tweaker" with his procedure
 - result- icon shows correctly on the taskbar.
So that problem only relates to the modern Metro/ UWP apps.



As for icon refresh issues on Classic/Open-Shell sorry, the thread kind of branched off. 
This started happening when I upgraded to 1809, and again after the re-release.
Others have had mostly Metro/UWP apps icon cache  related issues before : 

http://classicshell.net/forum/viewtopic.php?f=7&t=8162&p=34996&hilit=cache#p34996

http://classicshell.net/forum/viewtopic.php?f=7&t=7922&p=34176&hilit=clear+cache#p34176


I've also had problems when Classic Shell upgraded from v4.3.0 to v4.3.1
This is more specific to lack of correct skinning information and version changes : 

http://classicshell.net/forum/viewtopic.php?f=17&t=8172


By the way, that last picture with the correct pinned Audacity icon changing into white file icon on the desktop shows, in that case, it is Windows cache issue.

**Comment by CTVCAM8** [comment] 2018-11-22 19:35
Here is an important link I found about pinned items making taskbar app icon invisible:

http://classicshell.net/forum/viewtopic.php?f=12&t=8123

Ensure "Pinned programs folder" setting is on the default "Use pinned folder" in "Main menu" tab settings.

**Comment by bert07** [comment] 2018-12-07 19:18
I just installed Open-Shell 4.4.131 on Windows 10 version1809. I had no problems what so ever.

- I uninstalled Classic Shell 4.3.1
- Reboot
- I installed Open-Shell-Menu 4.4.131
- Log out
- Log in
- Everything is as it was before without having to import anything

Having said that: I use very basic settings and the WindowsXP look.

**Comment by ibuprophen1** [comment] 2019-05-29 04:46
It looks like this issue has ultimately been resolved... 

Am I correct? 


~Ibuprophen

**Comment by ibuprophen1** [comment] 2019-06-03 16:34
I'm going to close this issue as Issuer Unresponsive to this submission. 

If necessary, the OP Issuer may open up a new issue. 

Thank you very much for your time, patience and understanding with this! 👍


~Ibuprophen

**Closed by ibuprophen1** 2019-06-03 16:34 UTC
Labels: Issuer Unresponsive

**Comment by Scattershor** [comment] 2019-12-13 08:39
I'd like to reopen this as I am having the same issue, and it still hasn't been fixed. Adding a shortcut to the OpenShell start menu will null the icon of a windows app store app. Even the Windows Store itself suffers from this issue.

**Comment by antonyupward** [comment] 2020-04-17 17:01
Windows 10 1909 Build 18363.720
Open Shell 4.4.143

Yes I'd like to reopen too... as I think my symptom is highly related...

In my case symptom is that UWP app **shortcuts** in OpenShell Start Menu (created from hidden  shell:AppsFolder) lose their icons **after reboot**; the short cut icons are replaced in Start Menu with blank document icons, see image:

![Blank UWP App Shortcut Icons](https://user-images.githubusercontent.com/33206258/79593998-480f9d80-80aa-11ea-88d6-4ffdd9e353c5.png)

I've tried all the tips in this thread - resetting the OpenShell and Windows Icon caches etc. - nothing works.    

The icons reappear when I create the shortcut and place this into C:\ProgramData\Microsoft\Windows\Start Menu\... and disappear upon reboot.
