### ISSUE TITLE
MS Surface, different behavior with touch and mouse

### ISSUE THREAD

**Issue by chk21** [Open-Shell/Open-Shell-Menu#1751] opened 2023-11-06 13:04 UTC
### Describe the bug

When you select "Start" with Touch (finger or pen), only the Windows Start menu is displayed.
If you do the same with the mouse, the Open Shell menu will be displayed.
This has been noticed on several Surface Pro 8 with Windows 11 and the 23H2 version.
Open Shell version 4.4.191

**Open with mouse**
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/150028512/dd1c6537-a343-4ffc-b88e-91bb9e57b42c)
.
.
.
**Open with finger or pen**
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/150028512/034ec862-7fdd-417d-831b-e03ee93f7fa3)

Menu Settings.xml (as txt - rename it)
[Menu Settings.txt](https://github.com/Open-Shell/Open-Shell-Menu/files/13266750/Menu.Settings.txt)

### Area of issue

Start menu

### To reproduce

Goto START

### Open-Shell version

4.4.191

### Windows version

Windows 11 - 23H2

**Comment by ge0rdi** [comment] 2023-11-06 13:34
This is duplicate of #1229.
Unfortunately we don't have any solution for that.

**Closed by ge0rdi** 2023-11-06 13:34 UTC
Labels: Bug
