### ISSUE TITLE
Explorer search box

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [Open-Shell/Open-Shell-Menu#712] opened 2021-05-11 14:13 UTC
Is there a way using any kind of hackery to disable the new Windows Explorer search box (the one present in Windows 10 1909, 2004, 20H2, 21H1 and later) and return to the old search box (from Windows 7 up to Windows 10 1903)? The new one is full of bugs, very badly behaved and the earlier search from Vista to 1809 was much better.

In 1909, there was a way to disable it using mach2 tool but that broke too in 2004 as Microsoft now forces it.

However I found that disabling UAC makes the old Explorer search return. So the old code is still there. There has to be a way to revive it and disable the new horrible Search.

**Comment by NebelNidas** [comment] 2021-05-19 19:43
Duplicate of / related to #302, #389, and #422. But thanks for the tip with disabling UAC!

**Comment by bonzibudd** [comment] 2021-05-19 19:46
One way I was able to temporarily disable it was by starting in the Control panel and then navigating to a folder using the address bar. Maybe that could work as a direct shortcut.

**Comment by anonimuos** [comment] 2021-05-20 08:16
Oh I am sorry about the duplicate posts. I did search using Google for anyone who may have posted it before using:
<search term> site:github.com/Open-Shell but I must have missed it somehow.

**Closed** 2022-11-25 21:04 UTC
Labels: Enhancement/Feature Request

**Comment by NebelNidas** [comment] 2022-11-25 22:28
Btw, Winaero Tweaker actually got an option for this a few releases back
