### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by michaelleepow90** [Open-Shell/Open-Shell-Menu#212] opened 2019-08-30 22:39 UTC
I've notice that on the GIT Forum that the latest version was 4.4.131.. But I have version 4.4.138. Did they forget to update the forum news post?
![44131](https://user-images.githubusercontent.com/25166581/64054562-012d6180-cb34-11e9-980d-578bad5cc34b.jpg)

**Comment by Ibuprophen** [comment] 2019-08-31 00:20
The Stable version is v4.4.131. 

The Nightly version is v4.4.138 (actually the latest Nightly version is v4.4.139). 

The difference between the Stable and Nightly is that the Nightly "may" be unstable. 

The Nightly versions have incremental fixes, patches, etc... that hasn't been deemed stable yet. Sometimes those said fixes, patches, etc... may have to be removed/reverted because it may not have worked out as intended (or for other reasons). 

I hope that I had explained this okay via text... 


~Ibuprophen

**Comment by thunderpants** [comment] 2019-09-02 17:43
I was just about to ask something similar :)
I saw this "Open Shell 4.4.135" :
https://www.techspot.com/downloads/7103-open-shell.html
Thought there was a new release.

**Comment by Ibuprophen** [comment] 2019-09-02 18:51
Just keep in mind that there's allot of websites that aren't Official and can/may provide comprised builds. 

The Github repository & its main page provides the Official Stable & Nightly Builds. 

I'm a developer for Android Apps that are also spread throughout various websites (Unofficially) and some/many are compromised and/or older versions. 

I'm going to close this issue as being answered. 

Thank you very much for your time and understanding with this and I hope that I've answered all your questions. 


~Ibuprophen

**Closed by Ibuprophen** 2019-09-02 18:51 UTC
