### ISSUE TITLE
Sleep option from start menu stopped working after Win10 2004 update

### ISSUE THREAD

**Issue by MJB500** [Open-Shell/Open-Shell-Menu#387] opened 2020-06-25 05:43 UTC
If I select "sleep" from the start menu (through Open-Shell) it does nothing. All other options work (shutdown, log off, restart, etc.). If I use Win+X and select sleep the computer goes into sleep mode. Is anyone else having this issue? Any work arounds?

**Comment by bonzibudd** [comment] 2020-06-26 04:25
I have just tried this myself, it works flawlessly. I would start by adding the "sleep" command to the custom shutdown menu items section in Open-Shell Menu settings. My other two suggestions would be to uninstall and reinstall Open-Shell, and uninstall the latest cumulative update from Windows if the previous suggestion doesn't work.

**Comment by MJB500** [comment] 2020-06-26 19:05
I have uninstalled and reinstalled Open-Shell. It do not change the behavior.

I added "lock" and  "hibernate"through Windows. Now when I select "sleep" from the OpenShell menu it "locks" instead of "sleeping". 

I have tried changing the "shutdown command" from shutdown to sleep within the OpenShell settings. This did not work either.

**Comment by NebelNidas** [comment] 2020-09-11 07:02
Perhaps it has something to do with this: https://lifehacker.com/how-to-fix-the-latest-windows-10-sleep-mode-bug-1845004205

I know this article refers to a September update and your bug report is from June, but many other users have reported similar issues since the release of 2004, so it could be related. 🤷‍♀️

On the other hand, if it works from everywhere else and only Open Shell causes this issue, it indeed has to be an error on Open Shell's side of things or your installation/Windows got corrupted somehow.

**Comment by iccfish** [comment] 2021-02-20 16:47
I think this issue was caused by 'Modren standby'. Many newly laptops using a new standby power model names [Modern Standby](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/modern-standby). I bought a device (Asus Moba 5 Plus) which only support S0(aka **connected standby**, or, **modern standby**) intead of S3(traditional sleep).

Although S0(modern standby) was tooooooo hard to use, it uses too much battery and produces more heat, less reliability, but it's the only option for now(only if MS change is mind and manufacture provides newer firmware, and OS reinstallation required).

But if S0 was enabled (can confirmed via `powercfg /a`), the sleep menu in open shell was broken, it just done nothing, but the sleep menu in windows 10 built-in start menu just works ok.

In additional, an event log was recorded after click sleep menu in open shell menu:
> 用户模式进程尝试通过调用 SetSuspendState 或 SetSystemPowerState API 更改系统状态。
> The user mode process attempted to change the state of the system by calling the SetSuspendState or SetSystemPowerState APIs.

**Comment by OhSoGood** [comment] 2021-03-23 22:58
+1. I exactly have the same behavior.

**Comment by ge0rdi** [comment] 2022-12-28 19:29
Should be fixed in [latest](https://github.com/Open-Shell/Open-Shell-Menu/releases) build.

**Closed by ge0rdi** 2022-12-28 19:29 UTC
Labels: Unable To Reproduce
