### ISSUE TITLE
OpenShell (current version) not loading on bootup

### ISSUE THREAD

**Issue by larryedwards** [Open-Shell/Open-Shell-Menu#635] opened 2021-02-04 05:32 UTC
**Describe the bug**
OpenShell is not loading on bootup, and I have to load it manually. It appears in AutoRuns, checked for loading at logon, as c:\program files\open-shell\startmenu.exe . That file exists at that location.

**To Reproduce**
Bootup the computer

**Expected behavior**
I expect OpenShell's start menu to load during bootup, automatically.

**Screenshots**

**Version:**
 - Open-Shell: [e.g. 4.4.160]
 - OS: [e.g. Windows 10 1909]

**Additional context**
n/a

**Comment by NebelNidas** [comment] 2021-02-10 12:02
Have you tried reinstalling Open-Shell? No data should be lost if you do so, so it should be worth a try.

**Comment by larryedwards** [comment] 2021-02-10 20:00
I uninstall, rebooted, reinstalled, and rebooted again - using the current version from your Github page. OpenShellMenu still does not load on bootup.

On my desktop, the icon has an adminstrator shield on it, and it requires permission to run manually. Perhaps it also lacks permission to load at bootup??
![ScreenShot](https://user-images.githubusercontent.com/3360573/107563956-2da13600-6b8e-11eb-8133-e679f519aa53.png)

In Autoruns (Logons tab), the "OpenShell Start Menu" item is checked, and is set to C:\program files\open-shell\startmenu.exe. That is in the HKLM\Software\Microsoft\Windows\Current Version\Run section.

My system is Win10 ver. 1909 (MS won't update it beyond that yet), and I have Eset antivirus.

What do you suggest?

**Comment by gruni217** [comment] 2021-02-19 12:42
I have the same problem here in 20H2. To reproduce the problem ist is sufficient to logoff and logon on Windows.
To Re-Enable the startmenu for the actual session ist es sufficient to run  C:\program files\open-shell\startmenu.exe again.
A functional workaround for me is to place a shortcut to  C:\program files\open-shell\startmenu.exe in the startup-folder in startmenu. This autostart comes "late-enough" to re-enable the menu.
The normal autostart under HKLM\Software\Microsoft\Windows\Current Version\Run exists.
I think this is a race-condition or a timing-problem.

**Comment by larryedwards** [comment] 2021-02-20 10:29
A bit of progress, thanks to your suggestion, gruni. Still one more step to go, though. 

I got a trial version of Chameleon Startup Manager, and moved OpenShell to the "Delay" column, in the #1 slot (first in the list). Then I moved a bunch of other non-essential startup services (program updates, etc.) to follow it in the delay column, while leaving everything else in the normal startup column.

Rebooting, OpenShell did load, but with the requirement for me to click Windows admin execution button for it. So, I still need to find out how to avoid that, although the bootup is no longer stepping over it.

Hope someone from the OpenShell team can help with that last bit.

**Comment by blackcrack** [comment] 2021-02-21 05:20
in VirtualBox works Win 10 2102:

Edition	Windows 10 Pro
Version	21H1
Installiert am	‎20.‎02.‎2021
Betriebssystembuild	19043.844
Leistung	Windows Feature Experience Pack 120.2212.551.0

and ![8gadgetpack](https://8gadgetpack.net/) too .. .. 
just for info ..

i guess, this issue can closed @larryedwards ,
you see the button commend & close by side of commend ? ;)

best

**Comment by larryedwards** [comment] 2021-02-21 09:15
I unchecked the box as you suggested, and rebooted.  Now OpenShell won't load at all (manually), so I am unable to recheck the box. I get Admin nag screen and click yes, but nothing happens, and there in no OpenShell process showing in ProcessExplorer.    ???

**Comment by blackcrack** [comment] 2021-02-21 11:17
so, then take a more new Windowsversion, i guess your serial should also works on a more new version (like i hope)
in any case is 1909 overaged and have many bugs who have the 2020 or 2021 not ..
I hope you have a Databook or some external harddisk for data-saving .. 
an other tip can i give you not.. because i be not your' WinNt supporter , i help on Open-Shell troubles if it's must be.
sometime must be an end with help.. you just have to recognize the limits .. and this is a WinNT limit ;)

best

p.s.: plz close the issue, thy

**Comment by gruni217** [comment] 2021-02-22 16:42
The issue was triggerd by a recent Windows-Update from MS. I have the same problem under 2004, 1909 and 1809 (LTSC), not only under 20H2. Also the older "Classic-Shell" has the same issue on those systems.

**Comment by larryedwards** [comment] 2021-02-22 18:04
In reply to blackcrack, the available Win10 versions beyond 1909 cause hardware driver related BSODs on Lenovo Thinkpads (what I have) and some Dell and HP models. Multiple sources advise not to force-install the 2004, 20H2 or 2021 versions until the update service allows a normal update. I am following that advice.

**Comment by NebelNidas** [comment] 2021-02-24 10:06
Running this command doesn't fix the issue either, does it? `%ProgramFiles%\Open-Shell\StartMenu.exe -upgrade -silent` (see [here](https://github.com/Open-Shell/Open-Shell-Menu/wiki/OS-upgrade-without-user-interaction))

**Comment by blackcrack** [comment] 2021-02-24 15:59
oh.. damn.. we have a wiki ! \*bg* .. f... yea !

**Closed** 2022-11-25 21:20 UTC
