### ISSUE TITLE
Open Shell menu doesn't show in Windows 10 21H1

### ISSUE THREAD

**Issue by MeesterJur** [Open-Shell/Open-Shell-Menu#819] opened 2021-08-17 09:29 UTC
Hi. I'm completely new to GitHub (not a programmer, either; just a high school math teacher), so I'm not quite sure if this is even the right way and/or place to report this vexing issue.

We (that is, my parents and I) have been using Classic Shell for the last several years. (As of late 2019, we've been using Classic Shell v. 4.3.1.) On August 15, my Dad's Classic Shell menu suddenly disappeared. Whenever the Start menu button (or the Win key) was pressed, there was just the briefest of flashes, but no menu. The default Windows 10 menu is working OK (Shift-click on the Start button or Shift+Win key works just fine); it's just the Classic stuff that seems to have vanished. (All our PCs are running Windows 10, 21H1.)

At first, I tried to run ClassicShellSetup_4_3_1.exe using the [Repair] option; this didn't solve anything. Next, I exported the settings (see the attached file), 
[(Classic Shell) Menu Settings.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/6998693/Classic.Shell.Menu.Settings.zip)
unistalled Classic Shell (using the ClassicShellSetup_4_3_1.exe installer), rebooted and installed Open Shell 4.4.160.

To our dismay, the issue remains: the Open Shell menu simply doesn't show. For the Open Shell settings, see the attached file 
[20210817 (Open Shell) Menu Settings.zip](https://github.com/Open-Shell/Open-Shell-Menu/files/6998701/20210817.Open.Shell.Menu.Settings.zip)

Currently, I'm at a loss. I ran **chkdsk** on the system disk, and everything seems fine. The OS is up to date, and everything else seems to be working as intended. Please advice.

Kind regards, Jur Groot.

**Comment by thisismy-github** [comment] 2021-08-17 13:42
You're not alone: #795, #804, #809, #817, etc. This is caused by the new News and Interests taskbar panel, which only appears while the taskbar is positioned at the bottom. It has several bugs that are caused by the panel being enabled while on an "unsupported" taskbar position, and it's not limited to just Open/Classic Shell.

To fix: have your Dad move his taskbar to the bottom, right click the taskbar, disable the news and interests panel, and restore his taskbar. Everything should be back to normal afterwards.

**Comment by kirkw** [comment] 2021-08-17 16:34
Thank you SO MUCH.  This fixed it on my "test VM", I forgot HOW MUCH I HATE The MSFT Start Button.
And these "New Features, I've NEVER ASKED FOR!"

**Comment by MeesterJur** [comment] 2021-08-17 20:42
**You have my undying gratitude.** Not only did it solve our Classic/Open Shell issues, other niggling errors disappeared as well. Our sanity is safe!

And as for these so-called "features": long ago, there was a MUF-compilation (Microsoft Undocumented Features). What we need now is a new MUF: Microsoft's Unwanted Features.

**Comment by jhgreene** [comment] 2021-08-18 07:59
awesome thank you

**Comment by JimTudeski** [comment] 2021-08-23 07:28
Same problem here. After the latest win10 update i can't open Classic Shell v. 4.3.1.. When i click on the start button the menu open but after it close itself fast. I tried to reinstall nothing. After this is found Open Shell 4.4.160. but same issue with this.

**Comment by rcoleman1943** [comment] 2021-08-24 01:23
See https://www.tenforums.com/software-apps/183807-classic-shell.html for solution.

**Comment by Aokromes** [comment] 2021-10-03 12:30
duplicate https://github.com/Open-Shell/Open-Shell-Menu/issues/795 @ge0rdi @coddec

**Closed** 2022-11-19 16:20 UTC
