### ISSUE TITLE
Tasks of the settings app are missing

### ISSUE THREAD

**Issue by ale5000-git** [Open-Shell/Open-Shell-Menu#488] opened 2020-10-04 13:56 UTC
**Describe the bug**
See tasks of the settings app in Open-Shell, it is empty.

**Expected behavior**
I would like to see the same tasks of the one of Windows.

**Screenshots**
Tasks of the settings app are missing.

Open-Shell:
![openshell-settings-tasks](https://user-images.githubusercontent.com/15793015/95017410-7b92b400-0659-11eb-9613-b8647d56b0e7.png)

Windows:
![win-settings-tasks](https://user-images.githubusercontent.com/15793015/95017413-7f263b00-0659-11eb-965f-a672fad7fc74.png)

**Version:**
 - Open-Shell: [e.g. 4.4.160]
 - OS: [e.g. Windows 10 1909]

**Comment by ge0rdi** [comment] 2020-10-04 14:41
There are no `Tasks` associated with `Settings` app jump-list.
Currently it reports one _unknown_ category of jump-list that we don't support (I really don't know what's in there, but standard windows start menu doesn't show anything useful as well (`Pin to start` and `Pin to taskbar` is present also in `Open-Shell`'s context menu).

So we'd just disable jump-lists for `Settings` app, to not show empty list needlessly.

**Comment by ale5000-git** [comment] 2020-10-04 14:46
There is one thing useful, the settings of the settings app (the last element), it isn't the same of opening it.

**Comment by ge0rdi** [comment] 2020-10-04 14:48
Well, but these `App settings` are not shown for any Modern application in `Open-Shell`.
I guess it is valid to request showing them in context menu. So please create new issue for that.

And please, don't create duplicate issues.

**Comment by ge0rdi** [comment] 2020-10-04 14:49
Duplicate of #487.

**Closed by ge0rdi** 2020-10-04 14:49 UTC

**Comment by ale5000-git** [comment] 2020-10-04 14:50
Sorry, it was proably a bug on Github, the first time it reported 404 but apparently it has still created the issue.

**Comment by ale5000-git** [comment] 2020-10-04 15:01
New issue here: #489
