### ISSUE TITLE
Auto import XML file on install

### ISSUE THREAD

**Issue by tsherrington** [Open-Shell/Open-Shell-Menu#403] opened 2020-07-16 23:17 UTC
This is a fantastic program, and I very much appreciate it.  I'm trying to automate the install, and while it's nice to be able to do a silent install, it would be great to have a way import the settings.xml from the command line.  I'd like to be able to do it at install, but also as a "reset to default" option if someone screws up their Start Menu.

**Comment by Ibuprophen** [comment] 2020-07-17 21:13
There's an import/export feature for the xml file already within the Open Shell settings window (at the bottom). 

Unless I'm not clear with your question... 


~Ibuprophen

**Comment by ge0rdi** [comment] 2020-07-18 07:03
@tsherrington 
I guess this is duplicate of #251 .
Or do you want something different?

**Comment by tsherrington** [comment] 2020-07-19 11:43
Yes, you're right.  It's a duplicate of 251.  Feel free to delete this one.

**Closed** 2020-07-19 11:43 UTC
Labels: Enhancement/Feature Request
