### ISSUE TITLE
Tasks of the settings app are missing

### ISSUE THREAD

**Issue by ale5000-git** [Open-Shell/Open-Shell-Menu#487] opened 2020-10-04 13:56 UTC
**Describe the bug**
See tasks of the settings app in Open-Shell, it is empty.

**Expected behavior**
I would like to see the same tasks of the one of Windows.

**Screenshots**
Tasks of the settings app are missing.
Windows:
![win-settings-tasks](https://user-images.githubusercontent.com/15793015/95017413-7f263b00-0659-11eb-965f-a672fad7fc74.png)
Open-Shell:
![openshell-settings-tasks](https://user-images.githubusercontent.com/15793015/95017410-7b92b400-0659-11eb-9613-b8647d56b0e7.png)

**Version:**
 - Open-Shell: [e.g. 4.4.160]
 - OS: [e.g. Windows 10 1909]

**Comment by bonzibudd** [comment] 2020-10-04 14:12
These options are available in the right-click menu. However for the other issue, the (Empty) text, it is apparently caused by Windows reporting that there should be items there, but there aren't any. I believe this will be fixed soon.

**Comment by ge0rdi** [comment] 2020-10-04 14:50
We will disable jump-lists for `Settings` app as there is nothing to show there currently.

**Closed** 2020-10-23 08:14 UTC
Labels: Acknowledged/Being Looked Into by Dev's
