### ISSUE TITLE
newly installed programs won't sort  version 4.4.131

### ISSUE THREAD

**Issue by vtrasikis** [Open-Shell/Open-Shell-Menu#263] opened 2019-11-29 04:35 UTC
**Describe the bug**
Newly installed programs are at the bottom of the listing and are NOT automatically sorted.  Saw the same problem from before, but with this version I can't find the auto arrange option

**Comment by ge0rdi** [comment] 2019-11-29 06:16
Open `All Programs` menu, right click on some item. There should be `Sort by Name` and `Auto Arrange` menu items.
Make sure you have `Auto Arrange` enabled (there should be check sign near it).

If you don't have such items, try to install latest 4.4.142.

**Comment by ge0rdi** [comment] 2020-08-31 19:06
I'm closing this.
Feel free to reopen, if the issue is still there.

**Closed by ge0rdi** 2020-08-31 19:06 UTC

**Comment by CarterSnich** [comment] 2021-07-03 13:10
May I ask? Shouldn't be that the "Apps" folder (folder for installed UWP apps) is on the top of all folders?
![image](https://user-images.githubusercontent.com/52433531/124355318-09c8b480-dc43-11eb-9612-6639833ab627.png)
