### ISSUE TITLE
KB5005033 Win 10 21H1 breaks openshell on HP pavilion  p7-1280t

### ISSUE THREAD

**Issue by dmaclip** [Open-Shell/Open-Shell-Menu#817] opened 2021-08-16 20:38 UTC
pc specs
https://support.hp.com/id-en/document/c03184959
when KB5005033 installed on Win 10 21H1 openshell start button (no matter if custom buttons used or not) when pressing start button menu just flashes and disappears.
uninstalling update fixes it.

**Comment by RobFro96** [comment] 2021-08-17 05:02
+1
on my laptop: https://www.asus.com/de/Commercial-Laptops/ASUSPRO-B8230UA/
same windows update
tried unistalling, switching between ClassicShell & OpenShell, resetting configuration -> nothing works

**Comment by thisismy-github** [comment] 2021-08-17 13:44
This is caused by the new News and Interests taskbar panel, which only appears while the taskbar is positioned at the bottom. It has several bugs that are caused by the panel being enabled while on an "unsupported" taskbar position, and it's not limited to just Open Shell.

To fix: move your taskbar to the bottom, right click the taskbar, disable the news and interests panel, and restore your taskbar. Everything should be back to normal afterwards.

**Comment by dmaclip** [comment] 2021-08-17 15:14
and yet on the hp I linked the taskbar is on top and the news and interests is disabled so....

**Comment by thisismy-github** [comment] 2021-08-17 15:17
Are you sure its disabled, or is it simply not appearing? Does it work if you just have the taskbar on the bottom in general, regardless of the panel being enabled or not?

**Comment by dmaclip** [comment] 2021-08-17 15:20
does not work in any way shape or form on this pc with that update installed.

**Comment by blackcrack** [comment] 2021-08-17 16:37
well, if it's like you say (i use Win7 still, because it works easy..)
then it's at time to bring more and more programmers to Reactos.org 
to have an Opensource WinNT instead the commercial WinNt from MS,
MS takes every more and more out, to bring the Peoples 1. as customers and in 4 corners who 
it is impossible for customizing the Win11 like the User it want..
i get an ever bigger frustration if i see where the way of Win11 goes and the Updates from Win10..
Make advertising for reactos.org, speak with friends about reactos.org and 
look for bring more programmer to reactos.org ...  
best

**Comment by dmaclip** [comment] 2021-08-17 17:25
> 
> 
> let me try moving toolbar, re-enabling news/interests then disabling and installing update

ok had to move toolbar to bottom, re-enable (as it was disabled) and restart (restart seemed to be important) then disable move toolbar and installed update.
seems fine so far.
21H1 included some admx files for this I'll use to also disable through gpo

**Comment by dmaclip** [comment] 2021-08-17 17:26
> 
> 
> > let me try moving toolbar, re-enabling news/interests then disabling and installing update
> 
> ok had to move toolbar to bottom, re-enable (as it was disabled) and restart (restart seemed to be important) then disable move toolbar and installed update.
> seems fine so far.
> 21H1 included some admx files for this I'll use to also disable through gpo

has nothing to do with the issue. this is a program for windows not gnu/linux

**Comment by garkin** [comment] 2021-08-19 00:14
I do not have 21H1 and Security update KB5005033 still broken Classic Shell for me, had to uninstall update.

**Comment by Aokromes** [comment] 2021-10-03 12:40
"fix" on
#795 (comment)
@ge0rdi @coddec i suggest to close this because the one i link have better information.

**Closed** 2022-11-19 16:21 UTC
