### ISSUE TITLE
ungroup taskbar icons option and show labels option

### ISSUE THREAD

**Issue by morrow95** [Open-Shell/Open-Shell-Menu#1351] opened 2023-03-08 01:10 UTC
### Is your feature request related to a problem? Please describe.

Ability to ungroup the Windows 11 taskbar icons and show labels - similar to how Windows 10 allowed.  I previously used Explorer Patcher to do this, but recently either an update with it or Windows Update caused volume/brightness flyouts to no longer show when using it.

I get it... this is for the start menu only, but you do have taskbar options in here as well.  Consider adding this as a feature.  Other competing products (startallback) offer this.

### Describe the solution you'd like

Ability to ungroup the Windows 11 taskbar icons and show labels - similar to how Windows 10 allowed.

### Area of issue

Taskbar

**Comment by ge0rdi** [comment] 2023-03-08 07:01
I think this is duplicate of #1140.

**Closed by ge0rdi** 2023-03-08 07:01 UTC
Labels: Enhancement/Feature Request
