### ISSUE TITLE
After changing the logoff command in Log off menu item, the item's caption contains special characters instead of user's name.

### ISSUE THREAD

**Issue by Anixx** [Open-Shell/Open-Shell-Menu#872] opened 2021-10-09 18:42 UTC
In fact it displays just %s in the menu, not the user name.

**Comment by ge0rdi** [comment] 2022-12-11 11:49
@Gaurav-Original-ClassicShellTester 
Could you, please, provide exact steps how to reproduce the issue?

**Comment by bonzibudd** [comment] 2022-12-26 07:10
@ge0rdi 

Here's how to reproduce:
1. Use Single-column classic style menu
2. Edit "Log Off" item under Customize Start Menu:
![image](https://user-images.githubusercontent.com/61938331/209516125-85135414-e90f-4085-933d-7151c84fe2bf.png)
3. The Log Off item now looks like this:
![image](https://user-images.githubusercontent.com/61938331/209516205-0f78535c-6a52-41af-a6c5-04df52d8a42a.png)

I could see a fix for this being helpful if someone uses a custom program for shutdown.

**Comment by ge0rdi** [comment] 2022-12-26 21:08
User name is substituted only in case of built-in `logoff` command.

There is no way to know that we should replace `%s` in arbitrary custom command's description with user name (it would make no sense to do so for most commands).

I'd recommend to use `$Menu.LogOffShort` label if you want custom logoff command.
That way it will show as `Log Off` in menu.

**Closed by ge0rdi** 2022-12-26 21:08 UTC
