### ISSUE TITLE
Is there a way to make the start button replacement work better on Windows 11?

### ISSUE THREAD

**Issue by Jaladhjin** [Open-Shell/Open-Shell-Menu#1122] opened 2022-08-24 04:26 UTC
**Is your feature request related to a problem? Please describe.**

Yes when replacing the Start Button the shell icon seems to do the best job but you can still click around it a small bit to get the original Windows menu it's not a true button replacement.

I've tried a Windows 10 style button replacement too but same issue if I don't click in the correct place the original Windows menu comes up since it doesn't seem to be a true button replacement

**Describe the solution you'd like**

Replace the Start button better please!

**Describe alternatives you've considered**

StartAllBack seems to work fine in replacing the Start button perhaps a bit of collaboration on button replacement

**Additional context**

**Comment by blackcrack** [comment] 2022-08-24 05:29
@ge0rdi .. Trollpost (look the other post of him at his account..)

**Comment by ge0rdi** [comment] 2022-08-24 08:37
Duplicate of #780 #911.

**Closed by ge0rdi** 2022-08-24 08:37 UTC
Labels: Enhancement/Feature Request
