### ISSUE TITLE
Search Box does not find Windows settings

### ISSUE THREAD

**Issue by PeteM92** [Open-Shell/Open-Shell-Menu#229] opened 2019-09-23 06:48 UTC
Searching for "Ransomware" e.g. in the search box does not find any Windows settings.
Thus the search box does not work like Windows search or Cortana search, where settings menu for Ransomware Protection ist found correctly.

**Comment by ge0rdi** [comment] 2019-09-23 09:51
Duplicate of #57

**Closed by ge0rdi** 2019-09-23 09:51 UTC

**Comment by PeteM92** [comment] 2019-09-23 10:50
Thank you ge0rdi,
this seems to be an old isssue, which is still not resolved.

**Comment by ge0rdi** [comment] 2019-09-23 10:57
> this seems to be an old issue, which is still not resolved.

Unfortunately we have no solution yet :(
