### ISSUE TITLE
Windows 10 update 20H2 makes Classic Shell/Open Shell  unusable

### ISSUE THREAD

**Issue by Kman780** [Open-Shell/Open-Shell-Menu#730] opened 2021-05-30 06:09 UTC
Hi there. After a (forced) Windows 10 update to 20H2 version, Open Shell/Classic Shell, appears to be changing from off and on, or active and deactivated, in short, the bar is constantly changing from transparent to normal (Windows just installed), and the screen is flashing, making it impossible to use the PC.  Discovered the cause was Open Shell/Classic Shell as when I uninstalled it, desktop returned to normal, not flashing anymore and PC usable again.

Tried the standard uninstall and reinstall of Classic  Shell 4.3.1 (which worked perfectly prior to this Windows update) and then tried same with Open Shell 4.4.160, uninstall, reinstall, still the same issue.   Had to uninstall Classic Shell/Open Shell just to make my computer usable again but now stuck with the Windows 10 standard Start Menu.

Been a fan/loyal user of Classic Shell/Open Shell for 5+ yrs now. Can you investigate as I’ve read others in this forum have had similar issue and hope for a fix for current version of Open Shell to make it usable with new Windows 10 update 20H2.

**Version:**
 - Classic Shell 4.3.1/Open-Shell: 4.4.160
 - OS: Windows 10 - 20H2 update

**Comment by IanMenz1** [comment] 2021-06-11 08:24
> 
> 
> Hi there. After a (forced) Windows 10 update to 20H2 version, Open Shell/Classic Shell, appears to be changing from off and on, or active and deactivated, in short, the bar is constantly changing from transparent to normal (Windows just installed), and the screen is flashing, making it impossible to use the PC. Discovered the cause was Open Shell/Classic Shell as when I uninstalled it, desktop returned to normal, not flashing anymore and PC usable again.
> 
> Tried the standard uninstall and reinstall of Classic Shell 4.3.1 (which worked perfectly prior to this Windows update) and then tried same with Open Shell 4.4.160, uninstall, reinstall, still the same issue. Had to uninstall Classic Shell/Open Shell just to make my computer usable again but now stuck with the Windows 10 standard Start Menu.
> 
> Been a fan/loyal user of Classic Shell/Open Shell for 5+ yrs now. Can you investigate as I’ve read others in this forum have had similar issue and hope for a fix for current version of Open Shell to make it usable with new Windows 10 update 20H2.
> 
> **Version:**
> 
>     * Classic Shell 4.3.1/Open-Shell: 4.4.160
> 
>     * OS: Windows 10 - 20H2 update

I am also having similar issues. I think it has to do with the new news and interests widget for the taskbar. I found that changing the settings for that affected whether my taskbar would be usable or not. Hopefully a new update for OpenShell will fix this.

**Comment by blackcrack** [comment] 2021-06-11 09:30
well... here works pretty well..

![Screen 00001](https://user-images.githubusercontent.com/7925717/121664929-4a9c3600-caa8-11eb-8ffa-6f76c9063553.jpg)

**Comment by IanMenz1** [comment] 2021-06-11 19:02
Now I think it has to do with another taskbar program called BatteryBarPro. After I turned off the auto start for that program, no issues came up. I will redownload OpenShell and test it out without the battery app running.

**Comment by Randall-Glass** [comment] 2021-06-30 13:02
In windows 10 update 20H2 the taskbar is messed up.

It shows a white bar in the middle

![windows 10 update 20H2](https://imgur.com/7ekwvjw)

**Comment by blackcrack** [comment] 2021-06-30 13:18
@Randall-Glass i can not open the picture , not with Firefox and also not with Edge

**Comment by Randall-Glass** [comment] 2021-06-30 15:12
Could not get the picture to display myself.

The picture is located at

https://i.imgur.com/7ekwvjw.png

**Comment by blackcrack** [comment] 2021-07-01 04:32
@Randall-Glass 
1. you need only save as jpg, then works to put via plug'nPlay in the comment , then works, like my picture..
2. which version of OpenShell it is ? Right Mouseklick on the Startbutton, klick Configuration.. and let show directly the Window where show the Version of the Windows (Open the Explorer, right mouseklick in Explorer => "My PC" , Arrange it like my example then make a Screenshot and save it as jpg ...

3rd .. the Apple / IPhone advertising in the background hurts for me already a lil bit for me... 
( looking the picture and think me... really ??? ) \*very big grin*

This actually picture is really less meaningful.. looks like a Joke .. with this screenshot blame yourself ... \*lol*

![Screen 00000](https://user-images.githubusercontent.com/7925717/124064968-1e842d00-da36-11eb-9ee0-53d9cbab8043.jpg)

**Comment by IanMenz1** [comment] 2021-07-01 04:40
This whole issue was caused by the Windows Update, but the newest Windows Update fixed all the issues for me

**Comment by Randall-Glass** [comment] 2021-07-01 07:54
I am using the latest version of open shell Version 4.4.160

IanMenz1 what newest Windows Update did you do?

My windows 10 feature update 20H2 took forever to do.

Did you do a new windows feature update? Or was it just a ordinary update.

My windows 10 20H2 has done several updates since then.

And yet that ugly white space is still the task bar.

**Comment by Randall-Glass** [comment] 2021-07-01 08:08
To blackcrack: Of course your version is working. You only got Windows 10 feature update
20H1 on your system.

We are talking about open shell not working Windows 10 feature update 20H2.

**Comment by blackcrack** [comment] 2021-07-01 11:05
@Randall-Glass, Randell, your picture is less meaningful, because i am told you, you should make again a screenshot with open Configurationswindow of OpenShell and Open WinNT Configuration where be able your WinNt, it's clear to have an other version like you, but some Screenshoot can i found also a screenshoot with Google pictures... how ever, @IanMenz1 have told what's you need for resolve that.. update your system and you could be happy ;)

**Comment by IanMenz1** [comment] 2021-07-01 15:10
Read this, however, I think my June preview update was the one that fixed this for me. Disabling the weather widget did not do much. https://www.windowslatest.com/2021/05/31/kb5003214-update-is-causing-issues-with-windows-10-taskbar/

**Comment by anonimuos** [comment] 2021-07-06 05:21
So far no issues for me on 20**H2** but maybe some specific settings of Open Shell or Windows customizations are causing it? Note all different from defaults you've changed or programs you've installed that customize the taskbar.

For me so far it's working fine on 20H2 and even 21H1 and Windows 11 (once you do the classic Taskbar tweak) except system date is broken but that's not related to Classic/Open Shell.

**Comment by Randall-Glass** [comment] 2021-07-07 15:51
Uninstall the June update. 

It did not help any.

**Comment by blackcrack** [comment] 2021-07-15 05:16
> 
> 
> 21H1 Open-Shell works just fine. I never had issues before that either.

2nd

**Comment by Balmforthk810** [comment] 2021-09-07 11:52
Hi,

    I started with a Windows 10 1903 Vmware WM running Classic Shell 4.3.1.

    I used Windows Update to upgrade to Windows 10 20H2 and Classic Shell continued to work fine.

    I then went back to the Windows 10 1903 Vmware WM and upgraded straight to Windows 10 21H1 using this link:- https://www.microsoft.com/en-us/software-download/windows10 

    Again, Classic Shell continued to work fine. 

    As someone earlier said, perhaps certain Classic Shell settings cause a problem. I can post my settings if required,

    Regards,

    Kevin

**Comment by Aokromes** [comment] 2021-10-03 12:39
"fix" on 
https://github.com/Open-Shell/Open-Shell-Menu/issues/795#issuecomment-897043312
@ge0rdi @coddec i suggest to close this because the one i link have better information.

**Closed** 2022-11-19 16:25 UTC
